/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uwowikiaaid;

import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.io.UnsupportedEncodingException;
import java.util.HashSet;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Simon
 */
public class Books extends javax.swing.JFrame {

    
    public class recipe{
        
 String RecipeName,recipeinfo,RecipeLevel;
 String item1, item2, item3, itemQuant1,itemQuant2, itemQuant3;
 String product1 , product2, productquant1, productquant2;
     public void setRecipeName( String Name ){
         RecipeName = Name;
     } 
     public void setRecipeInfo(String RecipeInfo)
     {
         recipeinfo = RecipeInfo;
     }
     
     public void SetRecipeLevel(String recipelevel)
     {
         RecipeLevel = recipelevel;
     }
     
     public void SetItem(String Item1, String Item2, String Item3)
     {
         item1 =  Item1;
         item2 =  Item2;
         item3 =  Item3;
                
     }
     public void SetItemQuantity (String ItemQ1, String ItemQ2, String ItemQ3)
     {
         
         itemQuant1 = ItemQ1;
         itemQuant2 = ItemQ2;
         itemQuant3 = ItemQ3;
     }
     public void SetProduct (String Product1, String Product2)
     {
         product1 = Product1;
         product2 = Product2;
     }
     public void SetProductQuantity (String ProductQ1, String ProductQ2 )
     {
         productquant1 = ProductQ1;
         productquant2 = ProductQ2;
     }
     
     public String GetRecipeName()
     {
         return RecipeName;
     }
}
    /**
     * Creates new form Books
     */
    public Books() {
        this.Recipes = new recipe[20];
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frmRecipe = new javax.swing.JFrame();
        txtRName = new javax.swing.JTextField();
        txtRInfo = new javax.swing.JTextField();
        cboxRankReqR = new javax.swing.JComboBox<>();
        txtIngredients1R2 = new javax.swing.JTextField();
        txtProduct1 = new javax.swing.JTextField();
        txtProduct2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cboxIngredientQuantity3 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        cboxProductQuantity2 = new javax.swing.JComboBox<>();
        cboxProductQuantity1 = new javax.swing.JComboBox<>();
        btnAddRecipe1 = new javax.swing.JButton();
        txtIngredients1R1 = new javax.swing.JTextField();
        txtIngredients1R3 = new javax.swing.JTextField();
        cboxIngredientQuantity1 = new javax.swing.JComboBox<>();
        cboxIngredientQuantity2 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btnAnotherRecipe = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtBookName = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtskillreq = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cboxRankReq1 = new javax.swing.JComboBox<>();
        cboxRankReq2 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtdesc = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtAqs = new javax.swing.JTextField();
        btnLockInfo = new javax.swing.JButton();
        cboxNoOfRecipes = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstRecipes = new javax.swing.JList<>();
        jLabel17 = new javax.swing.JLabel();
        btnGenerateTemplate = new javax.swing.JButton();
        btnResetTemplate = new javax.swing.JButton();
        btnAddCity = new javax.swing.JButton();
        lblAqs = new javax.swing.JLabel();

        frmRecipe.setName("frmRecipe"); // NOI18N
        frmRecipe.setResizable(false);
        frmRecipe.setSize(new java.awt.Dimension(525, 514));

        cboxRankReqR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20" }));

        jLabel10.setText("Recipe Name:");

        cboxIngredientQuantity3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20" }));

        jLabel11.setText("Recipe Info:");

        cboxProductQuantity2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20" }));

        cboxProductQuantity1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20" }));

        btnAddRecipe1.setText("Add/change Recipe");
        btnAddRecipe1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddRecipe1MouseClicked(evt);
            }
        });

        cboxIngredientQuantity1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20" }));

        cboxIngredientQuantity2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20" }));

        jLabel8.setText("Required Rank");
        jLabel8.setToolTipText("");

        jLabel9.setText("Ingredient 1");

        jLabel12.setText("Ingredient 2");

        jLabel13.setText("ingredient 3");

        jLabel14.setText("Product 1");

        jLabel15.setText("Product 2");

        btnAnotherRecipe.setText("Next Recipe");
        btnAnotherRecipe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAnotherRecipeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout frmRecipeLayout = new javax.swing.GroupLayout(frmRecipe.getContentPane());
        frmRecipe.getContentPane().setLayout(frmRecipeLayout);
        frmRecipeLayout.setHorizontalGroup(
            frmRecipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmRecipeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(frmRecipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frmRecipeLayout.createSequentialGroup()
                        .addGroup(frmRecipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel10))
                        .addGroup(frmRecipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(frmRecipeLayout.createSequentialGroup()
                                .addGroup(frmRecipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(frmRecipeLayout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addComponent(txtIngredients1R3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(frmRecipeLayout.createSequentialGroup()
                                        .addGap(7, 7, 7)
                                        .addGroup(frmRecipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtIngredients1R2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtIngredients1R1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addGroup(frmRecipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cboxIngredientQuantity3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cboxIngredientQuantity2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cboxIngredientQuantity1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(frmRecipeLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(frmRecipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cboxRankReqR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(frmRecipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtRName, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtRInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(frmRecipeLayout.createSequentialGroup()
                        .addGroup(frmRecipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addGap(29, 29, 29)
                        .addGroup(frmRecipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtProduct1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtProduct2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(frmRecipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboxProductQuantity2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboxProductQuantity1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(frmRecipeLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btnAddRecipe1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAnotherRecipe)))
                .addContainerGap(159, Short.MAX_VALUE))
        );
        frmRecipeLayout.setVerticalGroup(
            frmRecipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmRecipeLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(frmRecipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frmRecipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(frmRecipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboxRankReqR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frmRecipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(frmRecipeLayout.createSequentialGroup()
                        .addGroup(frmRecipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIngredients1R1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(frmRecipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIngredients1R2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(frmRecipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIngredients1R3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)))
                    .addGroup(frmRecipeLayout.createSequentialGroup()
                        .addComponent(cboxIngredientQuantity1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboxIngredientQuantity2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboxIngredientQuantity3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frmRecipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addGroup(frmRecipeLayout.createSequentialGroup()
                        .addGroup(frmRecipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtProduct1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboxProductQuantity1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(frmRecipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtProduct2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(cboxProductQuantity2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(frmRecipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddRecipe1)
                    .addComponent(btnAnotherRecipe))
                .addContainerGap(81, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(525, 514));

        jLabel1.setText("Book Name");

        jLabel2.setText("Price:");

        jLabel3.setText("Skill Requirements:");

        jLabel4.setText("Level Required:");

        cboxRankReq1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20" }));

        cboxRankReq2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20" }));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("~");

        txtdesc.setColumns(20);
        txtdesc.setLineWrap(true);
        txtdesc.setRows(5);
        jScrollPane1.setViewportView(txtdesc);

        jLabel6.setText("Book Description;");

        jLabel7.setText("Aquisition");

        txtAqs.setToolTipText("");

        btnLockInfo.setText("Lock and input recipes");
        btnLockInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLockInfoMouseClicked(evt);
            }
        });
        btnLockInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLockInfoActionPerformed(evt);
            }
        });

        cboxNoOfRecipes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21" }));

        jLabel16.setText("How many recipes are in this book?");

        lstRecipes.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstRecipesValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(lstRecipes);

        jLabel17.setText("Recipes:");

        btnGenerateTemplate.setText("Generate Template:");
        btnGenerateTemplate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGenerateTemplateMouseClicked(evt);
            }
        });

        btnResetTemplate.setText("Reset Template");
        btnResetTemplate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnResetTemplateMouseClicked(evt);
            }
        });

        btnAddCity.setText("Add City");
        btnAddCity.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddCityMouseClicked(evt);
            }
        });

        lblAqs.setText("City:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel17))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(btnGenerateTemplate))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(43, 43, 43)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel1)
                                                    .addComponent(jLabel2)))
                                            .addComponent(jLabel3))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel4)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addComponent(jLabel7)))
                                .addGap(62, 62, 62)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtskillreq, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                                        .addComponent(txtPrice)
                                        .addComponent(txtBookName))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cboxRankReq1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cboxRankReq2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtAqs, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnAddCity))
                                    .addComponent(lblAqs, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cboxNoOfRecipes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(53, 53, 53)
                                        .addComponent(btnLockInfo)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnResetTemplate)))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtBookName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtskillreq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cboxRankReq1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboxRankReq2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtAqs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddCity))
                .addGap(5, 5, 5)
                .addComponent(lblAqs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboxNoOfRecipes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLockInfo)
                    .addComponent(btnResetTemplate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGenerateTemplate)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    recipe[] Recipes;

   int i= 1;
   
   String ItemQ1,ItemQ2,ItemQ3, ProductQ1, ProductQ2;
  DefaultListModel Recipelist = new DefaultListModel();
    private void btnAddRecipe1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddRecipe1MouseClicked
    // TODO add your handling code here:
        ItemQ1 = cboxIngredientQuantity1.getSelectedItem().toString();
        ItemQ2 = cboxIngredientQuantity2.getSelectedItem().toString();
        ItemQ3 = cboxIngredientQuantity3.getSelectedItem().toString();
        ProductQ1 = cboxProductQuantity1.getSelectedItem().toString();
        ProductQ2 = cboxProductQuantity2.getSelectedItem().toString();
        Recipes[i] = new recipe();
        Recipes[i].setRecipeName(txtRName.getText());
        Recipes[i].SetRecipeLevel(cboxRankReqR.getSelectedItem().toString());
        Recipes[i].setRecipeInfo(txtRInfo.getText());
        Recipes[i].SetItem(txtIngredients1R1.getText(), txtIngredients1R2.getText(), txtIngredients1R3.getText());
        Recipes[i].SetItemQuantity(ItemQ1, ItemQ2, ItemQ3);
        Recipes[i].SetProduct(txtProduct1.getText(), txtProduct2.getText());
        Recipes[i].SetProductQuantity(ProductQ1, ProductQ2);
        Recipelist.addElement(txtRName.getText());
       // TODO add your handling code here:
        
        if (i == 21)
        {
            frmRecipe.setVisible(false);
            btnLockInfo.setVisible(false);
        }
        lstRecipes.setModel(Recipelist);
     
    }//GEN-LAST:event_btnAddRecipe1MouseClicked

    private void btnLockInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLockInfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLockInfoActionPerformed
 
    String BookName,Price, SkillReq,RankReq1,RankReq2,Description;
    String GetNoOfRecipes;
    String Aquisition = "";
    
    private void btnLockInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLockInfoMouseClicked
        // TODO add your handling code here:
        BookName= txtBookName.getText();
        Price = txtPrice.getText();
        SkillReq = txtskillreq.getText();
        RankReq1 = cboxRankReq1.getSelectedItem().toString();
        RankReq2 = cboxRankReq2.getSelectedItem().toString();
        Description = txtdesc.getText();
        txtBookName.setEditable(false);
        txtPrice.setEditable(false);
        txtskillreq.setEditable(false);
        cboxRankReq1.setEditable(false);
        cboxRankReq2.setEditable(false);
        txtdesc.setEditable(false);
        txtAqs.setEditable(false);
        
        frmRecipe.setVisible(true);
        
    }//GEN-LAST:event_btnLockInfoMouseClicked
        
    private void lstRecipesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstRecipesValueChanged
        // TODO add your handling code here:
        int l = i;
        frmRecipe.setVisible(true);
        i = lstRecipes.getSelectedIndex();
        txtRName.setText(Recipes[i].RecipeName); 
        cboxIngredientQuantity1.setSelectedItem(Recipes[i].itemQuant1);
        cboxIngredientQuantity2.setSelectedItem(Recipes[i].itemQuant2);
        cboxIngredientQuantity3.setSelectedItem(Recipes[i].itemQuant3);
        cboxProductQuantity1.setSelectedItem(Recipes[i].productquant1);
        cboxProductQuantity2.setSelectedItem(Recipes[i].productquant2);
        cboxRankReqR.setSelectedItem(Recipes[i].RecipeLevel);
        txtRInfo.setText(Recipes[i].recipeinfo);
        txtIngredients1R1.setText(Recipes[i].item1);
        txtIngredients1R2.setText(Recipes[i].item2);
        txtIngredients1R3.setText(Recipes[i].item3);
        txtProduct1.setText(Recipes[i].product1);
        txtProduct2.setText(Recipes[i].product2);
        i = l;
    }//GEN-LAST:event_lstRecipesValueChanged

    private void btnAnotherRecipeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAnotherRecipeMouseClicked
        txtRName.setText(""); 
        cboxIngredientQuantity1.setSelectedIndex(0);
        cboxIngredientQuantity2.setSelectedIndex(0);
        cboxIngredientQuantity3.setSelectedIndex(0);
        cboxProductQuantity1.setSelectedIndex(0);
        cboxProductQuantity2.setSelectedIndex(0);
        cboxRankReqR.setSelectedIndex(0);
        txtRInfo.setText("");
        txtIngredients1R1.setText("");
        txtIngredients1R2.setText("");
        txtIngredients1R3.setText("");
        txtProduct1.setText("");
        txtProduct2.setText("");
        i++;        // TODO add your handling code here:
    }//GEN-LAST:event_btnAnotherRecipeMouseClicked

    private void btnGenerateTemplateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGenerateTemplateMouseClicked
        try {
               
            String lvformat, RecipeNo, Ing1,Ing2,Ing3; 
       
                    
            lvformat = cboxRankReq1.getSelectedItem().toString() + "~" + cboxRankReq2.getSelectedItem().toString();
            // TODO add your handling code here:
            String FileName = "C:/UWOTextFiles/Books/" +txtBookName.getText()+".txt";
            PrintWriter writer;
            
           
            writer = new PrintWriter(FileName, "UTF-8");
            writer.println("{{BookInfo |showrecipe={{{1|}}}");
            writer.println("|bookname = " + BookName);
            writer.println("|price = " + Price);
            writer.println("|skillreq = " + SkillReq);
            writer.println("|lv= " +"{{{lv|"+lvformat + "}}}");
            writer.println("|desc= " + Description);
            writer.println("|aqs =" + "[[" + Aquisition + "]]");
                  int k=1;
            do 
            {
           
                    RecipeNo = "recipe" + k ;
            String[] RecipeFormat = new String[5];
            Ing1 = Recipes[k].item1 + "\\" + Recipes[k].itemQuant1;
            if (Recipes[k].item2.isEmpty())
            {
                Ing2 = "";
            }else
            {
            Ing2 = Recipes[k].item2 + "\\"+ Recipes[k].itemQuant2;    
            }
             if (Recipes[k].item3.isEmpty())
            {
                Ing3 = "";
            }else
            {
            Ing3 = Recipes[k].item3 + "\\"+ Recipes[k].itemQuant3;
            }
            
            
            RecipeFormat[0]= "|" + RecipeNo + "=" + Recipes[k].RecipeName +";"+ "lv=" + Recipes[k].RecipeLevel+";";
            RecipeFormat[1]= "nfo= " + Recipes[k].recipeinfo + ";";
            RecipeFormat[2]= "ingredients=" + Ing1  +"," + Ing2 + "," + Ing3 + ";";
            
            RecipeFormat[3]= "product1=" +Recipes[k].product1 +"\\" + Recipes[k].productquant1 +";";
            if (Recipes[k].product2.isEmpty())
            {
                RecipeFormat[4] ="";
            }
            else
            {
                RecipeFormat[4]=  "product2=" +Recipes[k].product2 +"\\" + Recipes[k].productquant2 +";";
            }  
              
             
                    writer.println(RecipeFormat[0]);
                    writer.println(RecipeFormat[1]);
                    writer.println(RecipeFormat[2]);
                    writer.println(RecipeFormat[3]);
                    writer.println(RecipeFormat[4]);
                    
            k++;
            } while (k < Recipelist.getSize() + 1 );
            writer.println("}}");
            writer.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Books.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(Books.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGenerateTemplateMouseClicked

    private void btnResetTemplateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetTemplateMouseClicked
        // TODO add your handling code here:
        i = 0;
         txtRName.setText(""); 
        cboxIngredientQuantity1.setSelectedIndex(0);
        cboxIngredientQuantity2.setSelectedIndex(0);
        cboxIngredientQuantity3.setSelectedIndex(0);
        cboxProductQuantity1.setSelectedIndex(0);
        cboxProductQuantity2.setSelectedIndex(0);
        cboxRankReqR.setSelectedIndex(0);
        txtRInfo.setText("");
        txtIngredients1R1.setText("");
        txtIngredients1R2.setText("");
        txtIngredients1R3.setText("");
        txtProduct1.setText("");
        txtProduct2.setText("");
        txtBookName.setText("");
        txtPrice.setText("");
        txtskillreq.setText("");
        cboxRankReq1.setSelectedIndex(0);
         cboxRankReq2.setSelectedIndex(0);
         txtdesc.setText("");
         txtAqs.setText("");
        txtBookName.setEditable(true);
        txtPrice.setEditable(true);
        txtskillreq.setEditable(true);
        cboxRankReq1.setEditable(true);
        cboxRankReq2.setEditable(true);
        txtdesc.setEditable(true);
        txtAqs.setEditable(true);
        Recipelist.clear();
        lblAqs.setText("Cities:");
         
    }//GEN-LAST:event_btnResetTemplateMouseClicked

    private void btnAddCityMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddCityMouseClicked
        // TODO add your handling code here:
        lblAqs.setText(lblAqs.getText() + " " + txtAqs.getText());
        Aquisition = Aquisition + "[[" + txtAqs.getText() + "]]" + " ";
    }//GEN-LAST:event_btnAddCityMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
     //</editor-fold>
  try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Books().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCity;
    private javax.swing.JButton btnAddRecipe1;
    private javax.swing.JButton btnAnotherRecipe;
    private javax.swing.JButton btnGenerateTemplate;
    private javax.swing.JButton btnLockInfo;
    private javax.swing.JButton btnResetTemplate;
    private javax.swing.JComboBox<String> cboxIngredientQuantity1;
    private javax.swing.JComboBox<String> cboxIngredientQuantity2;
    private javax.swing.JComboBox<String> cboxIngredientQuantity3;
    private javax.swing.JComboBox<String> cboxNoOfRecipes;
    private javax.swing.JComboBox<String> cboxProductQuantity1;
    private javax.swing.JComboBox<String> cboxProductQuantity2;
    private javax.swing.JComboBox<String> cboxRankReq1;
    private javax.swing.JComboBox<String> cboxRankReq2;
    private javax.swing.JComboBox<String> cboxRankReqR;
    public javax.swing.JFrame frmRecipe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAqs;
    private javax.swing.JList<String> lstRecipes;
    private javax.swing.JTextField txtAqs;
    private javax.swing.JTextField txtBookName;
    private javax.swing.JTextField txtIngredients1R1;
    private javax.swing.JTextField txtIngredients1R2;
    private javax.swing.JTextField txtIngredients1R3;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtProduct1;
    private javax.swing.JTextField txtProduct2;
    private javax.swing.JTextField txtRInfo;
    private javax.swing.JTextField txtRName;
    private javax.swing.JTextArea txtdesc;
    private javax.swing.JTextField txtskillreq;
    // End of variables declaration//GEN-END:variables
}
