
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uwowikiaaid;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.UnsupportedEncodingException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.UIManager;
import static uwowikiaaid.CityTemplate.CraftShopInitialiser.CraftFileWrite;
import static uwowikiaaid.CityTemplate.ItemShopInitialiser.ItemFileWrite;
import static uwowikiaaid.CityTemplate.MarketInitiatliser.MarketFileWrite;
import static uwowikiaaid.CityTemplate.TavernInitialiser.tavernFileWrite;


/**
 *
 * @author Simon
 */
public class CitiesTemplate extends javax.swing.JFrame {

    /**
     * Creates new form CitiesTemplate
     */
    public CitiesTemplate() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frmMarket = new javax.swing.JFrame();
        txtTradeGood = new javax.swing.JTextField();
        txtPedlarItem = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstMarketGoods = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstPedlarGoods = new javax.swing.JList<>();
        btnAddTrade = new javax.swing.JButton();
        btnAddItem = new javax.swing.JButton();
        btnResetForm4 = new javax.swing.JButton();
        frmItemShop = new javax.swing.JFrame();
        jScrollPane4 = new javax.swing.JScrollPane();
        lstItemShop = new javax.swing.JList<>();
        jLabel6 = new javax.swing.JLabel();
        txtItemShop = new javax.swing.JTextField();
        btnsAddItem = new javax.swing.JButton();
        btnResetForm1 = new javax.swing.JButton();
        CraftShop = new javax.swing.JFrame();
        jLabel7 = new javax.swing.JLabel();
        txtCraftShop = new javax.swing.JTextField();
        btncAddItem = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        lstCraftShop = new javax.swing.JList<>();
        btnResetForm2 = new javax.swing.JButton();
        frmTavern = new javax.swing.JFrame();
        jLabel8 = new javax.swing.JLabel();
        txtTavern = new javax.swing.JTextField();
        btnAddTavernItem = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        lstTavern = new javax.swing.JList<>();
        jScrollPane7 = new javax.swing.JScrollPane();
        lstAide = new javax.swing.JList<>();
        btnAddAide = new javax.swing.JButton();
        txtAide = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnResetForm = new javax.swing.JButton();
        frmShipyard = new javax.swing.JFrame();
        frmContact = new javax.swing.JFrame();
        btnResetForm3 = new javax.swing.JButton();
        btnAddNPC = new javax.swing.JButton();
        jScrollPane10 = new javax.swing.JScrollPane();
        lstNPCs = new javax.swing.JList<>();
        jLabel13 = new javax.swing.JLabel();
        txtAddNPC = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescriptions = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        txtNameOfCity = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cboxRegion = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        btnMarket = new javax.swing.JButton();
        btnItemShop = new javax.swing.JButton();
        btnTavern = new javax.swing.JButton();
        btnCraftShop = new javax.swing.JButton();
        btnGenerateCityPage = new javax.swing.JButton();
        cboxLanguage = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        btnNPC = new javax.swing.JButton();
        btnClearTemplate = new javax.swing.JButton();

        frmMarket.setMinimumSize(new java.awt.Dimension(600, 600));

        txtPedlarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPedlarItemActionPerformed(evt);
            }
        });

        jLabel4.setText("Trade Good:");

        jScrollPane2.setViewportView(lstMarketGoods);

        jLabel5.setText("Pedlar Item");

        jScrollPane3.setViewportView(lstPedlarGoods);

        btnAddTrade.setText("Add Trade Good");
        btnAddTrade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddTradeMouseClicked(evt);
            }
        });

        btnAddItem.setText("Add Item");
        btnAddItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddItemMouseClicked(evt);
            }
        });

        btnResetForm4.setText("Reset Form");
        btnResetForm4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnResetForm4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout frmMarketLayout = new javax.swing.GroupLayout(frmMarket.getContentPane());
        frmMarket.getContentPane().setLayout(frmMarketLayout);
        frmMarketLayout.setHorizontalGroup(
            frmMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmMarketLayout.createSequentialGroup()
                .addGroup(frmMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frmMarketLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(frmMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(37, 37, 37)
                        .addGroup(frmMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(frmMarketLayout.createSequentialGroup()
                                .addComponent(txtPedlarItem, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnAddItem))
                            .addGroup(frmMarketLayout.createSequentialGroup()
                                .addComponent(txtTradeGood, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnAddTrade))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(frmMarketLayout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(btnResetForm4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        frmMarketLayout.setVerticalGroup(
            frmMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmMarketLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(frmMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTradeGood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(btnAddTrade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(frmMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPedlarItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(btnAddItem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnResetForm4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        frmItemShop.setMinimumSize(new java.awt.Dimension(400, 300));
        frmItemShop.setSize(new java.awt.Dimension(400, 300));

        jScrollPane4.setViewportView(lstItemShop);

        jLabel6.setText("Item:");

        txtItemShop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtItemShopActionPerformed(evt);
            }
        });

        btnsAddItem.setText("Add Item");
        btnsAddItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnsAddItemMouseClicked(evt);
            }
        });

        btnResetForm1.setText("Reset Form");
        btnResetForm1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnResetForm1MouseClicked(evt);
            }
        });
        btnResetForm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetForm1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout frmItemShopLayout = new javax.swing.GroupLayout(frmItemShop.getContentPane());
        frmItemShop.getContentPane().setLayout(frmItemShopLayout);
        frmItemShopLayout.setHorizontalGroup(
            frmItemShopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmItemShopLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(frmItemShopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frmItemShopLayout.createSequentialGroup()
                        .addComponent(txtItemShop, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnsAddItem))
                    .addComponent(btnResetForm1)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(78, Short.MAX_VALUE))
            .addGroup(frmItemShopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(frmItemShopLayout.createSequentialGroup()
                    .addGap(31, 31, 31)
                    .addComponent(jLabel6)
                    .addContainerGap(343, Short.MAX_VALUE)))
        );
        frmItemShopLayout.setVerticalGroup(
            frmItemShopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frmItemShopLayout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addGroup(frmItemShopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtItemShop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsAddItem))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnResetForm1)
                .addGap(32, 32, 32))
            .addGroup(frmItemShopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(frmItemShopLayout.createSequentialGroup()
                    .addGap(73, 73, 73)
                    .addComponent(jLabel6)
                    .addContainerGap(213, Short.MAX_VALUE)))
        );

        CraftShop.setMinimumSize(new java.awt.Dimension(600, 600));

        jLabel7.setText("Craft Shop Item:");

        txtCraftShop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCraftShopActionPerformed(evt);
            }
        });

        btncAddItem.setText("Add Item");
        btncAddItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncAddItemMouseClicked(evt);
            }
        });

        jScrollPane5.setViewportView(lstCraftShop);

        btnResetForm2.setText("Reset Form");
        btnResetForm2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnResetForm2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout CraftShopLayout = new javax.swing.GroupLayout(CraftShop.getContentPane());
        CraftShop.getContentPane().setLayout(CraftShopLayout);
        CraftShopLayout.setHorizontalGroup(
            CraftShopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CraftShopLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(CraftShopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btncAddItem)
                    .addGroup(CraftShopLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addGroup(CraftShopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(txtCraftShop, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(CraftShopLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(btnResetForm2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CraftShopLayout.setVerticalGroup(
            CraftShopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CraftShopLayout.createSequentialGroup()
                .addGroup(CraftShopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CraftShopLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(CraftShopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCraftShop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btncAddItem))
                    .addGroup(CraftShopLayout.createSequentialGroup()
                        .addGap(0, 110, Short.MAX_VALUE)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btnResetForm2)
                .addGap(17, 17, 17))
        );

        frmTavern.setMinimumSize(new java.awt.Dimension(600, 600));

        jLabel8.setText("Tavern Drink:");

        txtTavern.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTavernActionPerformed(evt);
            }
        });

        btnAddTavernItem.setText("Add Item");
        btnAddTavernItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddTavernItemMouseClicked(evt);
            }
        });

        jScrollPane6.setViewportView(lstTavern);

        jScrollPane7.setViewportView(lstAide);

        btnAddAide.setText("Add Aide");
        btnAddAide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddAideMouseClicked(evt);
            }
        });

        jLabel9.setText("Aide");

        btnResetForm.setText("Reset Form");
        btnResetForm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnResetFormMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout frmTavernLayout = new javax.swing.GroupLayout(frmTavern.getContentPane());
        frmTavern.getContentPane().setLayout(frmTavernLayout);
        frmTavernLayout.setHorizontalGroup(
            frmTavernLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmTavernLayout.createSequentialGroup()
                .addGroup(frmTavernLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frmTavernLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8))
                    .addGroup(frmTavernLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel9)))
                .addGap(18, 18, 18)
                .addGroup(frmTavernLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frmTavernLayout.createSequentialGroup()
                        .addComponent(btnResetForm)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(frmTavernLayout.createSequentialGroup()
                        .addComponent(txtAide, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addComponent(btnAddAide)
                        .addGap(70, 70, 70))
                    .addGroup(frmTavernLayout.createSequentialGroup()
                        .addGroup(frmTavernLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(frmTavernLayout.createSequentialGroup()
                                .addComponent(txtTavern, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnAddTavernItem))
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        frmTavernLayout.setVerticalGroup(
            frmTavernLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmTavernLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(frmTavernLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTavern, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(btnAddTavernItem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(frmTavernLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddAide)
                    .addComponent(txtAide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnResetForm)
                .addGap(12, 12, 12))
        );

        frmShipyard.setMinimumSize(new java.awt.Dimension(600, 600));

        javax.swing.GroupLayout frmShipyardLayout = new javax.swing.GroupLayout(frmShipyard.getContentPane());
        frmShipyard.getContentPane().setLayout(frmShipyardLayout);
        frmShipyardLayout.setHorizontalGroup(
            frmShipyardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        frmShipyardLayout.setVerticalGroup(
            frmShipyardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        frmContact.setMinimumSize(new java.awt.Dimension(600, 600));

        btnResetForm3.setText("Reset Form");
        btnResetForm3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnResetForm3MouseClicked(evt);
            }
        });

        btnAddNPC.setText("Add NPC");
        btnAddNPC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddNPCMouseClicked(evt);
            }
        });

        jScrollPane10.setViewportView(lstNPCs);

        jLabel13.setText("NPC:");

        txtAddNPC.setToolTipText("");

        javax.swing.GroupLayout frmContactLayout = new javax.swing.GroupLayout(frmContact.getContentPane());
        frmContact.getContentPane().setLayout(frmContactLayout);
        frmContactLayout.setHorizontalGroup(
            frmContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frmContactLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAddNPC)
                .addGap(50, 50, 50))
            .addGroup(frmContactLayout.createSequentialGroup()
                .addGroup(frmContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frmContactLayout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(btnResetForm3))
                    .addGroup(frmContactLayout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addGroup(frmContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAddNPC, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(149, Short.MAX_VALUE))
        );
        frmContactLayout.setVerticalGroup(
            frmContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frmContactLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(frmContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddNPC)
                    .addComponent(jLabel13)
                    .addComponent(txtAddNPC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(btnResetForm3)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtDescriptions.setColumns(20);
        txtDescriptions.setLineWrap(true);
        txtDescriptions.setRows(5);
        txtDescriptions.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtDescriptions);

        jLabel1.setText("Name:");

        jLabel2.setText("Port Permit:");

        cboxRegion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "North Atlantic Ocean", "West Mediterranean Sea", "East Mediterranean Sea", "North Sea", "Africa West Coast", "South Atlantic Ocean", "Africa East Coast", "The Red Sea", "The Indian Ocean", "Caribbean Sea", "E Coast of Latin America", "Southeast Asia", "South Pacific Ocean", "East Asia" }));

        jLabel3.setText("Description of City:");

        btnMarket.setText("Input Market Place");
        btnMarket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMarketMouseClicked(evt);
            }
        });

        btnItemShop.setText("Input Item Shop");
        btnItemShop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnItemShopMouseClicked(evt);
            }
        });

        btnTavern.setText("Tavern");
        btnTavern.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTavernMouseClicked(evt);
            }
        });

        btnCraftShop.setText("Craft Shop");
        btnCraftShop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCraftShopMouseClicked(evt);
            }
        });

        btnGenerateCityPage.setText("Generate Page");
        btnGenerateCityPage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGenerateCityPageMouseClicked(evt);
            }
        });

        cboxLanguage.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Language", "English", "Dutch", "German", "Nordic", "Celtic", "Portuguese", "Spanish", "French", "Italian", "Latin", "Slavic", "Greek", "Arabic", "Ancient Egyptian", "Hebrew", "Turkish", "West African languages", "Sawhili", "Persian", "Indian languages", "Mayan languages", "Nahuatl", "Quecha", "Thai/Burmese", "Mon-Khmer languages", "Malay/Tagalog", "Oceanic languages", "Chinese", "Japanese", "Korean" }));

        jLabel10.setText("Language:");

        btnNPC.setText("NPC Contact");
        btnNPC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNPCMouseClicked(evt);
            }
        });

        btnClearTemplate.setText("Clear Entire Template");
        btnClearTemplate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClearTemplateMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel1)
                                .addGap(47, 47, 47))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(txtNameOfCity, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnGenerateCityPage)
                                        .addGap(30, 30, 30)
                                        .addComponent(btnClearTemplate))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(btnNPC, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnCraftShop, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnTavern, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnItemShop, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnMarket, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(jLabel10))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboxRegion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboxLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNameOfCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cboxRegion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboxLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(btnMarket)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnItemShop)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCraftShop)
                .addGap(18, 18, 18)
                .addComponent(btnTavern)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNPC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGenerateCityPage)
                    .addComponent(btnClearTemplate))
                .addContainerGap(83, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPedlarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPedlarItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPedlarItemActionPerformed
DefaultListModel TradeGoods = new DefaultListModel();
ArrayList<String> Goods = new  ArrayList(30);

    private void btnAddTradeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddTradeMouseClicked
        // TODO add your handling code here:
    
        Goods.add("{{:" + txtTradeGood.getText() + "}}");
        TradeGoods.addElement(txtTradeGood.getText());
        lstMarketGoods.setModel(TradeGoods);
    }//GEN-LAST:event_btnAddTradeMouseClicked
DefaultListModel PedlarItems = new DefaultListModel();
ArrayList<String> Items = new ArrayList(30);

    private void btnAddItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddItemMouseClicked
        // TODO add your handling code here:
        PedlarItems.addElement(txtPedlarItem.getText());
        Items.add("{{:" + txtPedlarItem.getText() + "}}");
        lstPedlarGoods.setModel(PedlarItems);
    }//GEN-LAST:event_btnAddItemMouseClicked

    private void txtItemShopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtItemShopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtItemShopActionPerformed
DefaultListModel ItemShopItems = new DefaultListModel();
ArrayList<String> Itemshop = new  ArrayList(30);
int k = 0;
    private void btnsAddItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsAddItemMouseClicked
        // TODO add your handling code here:
        ItemShopItems.addElement(txtItemShop.getText());
        Itemshop.add("{{:" + txtItemShop.getText() + "}}");
	lstItemShop.setModel(ItemShopItems);
        
    }//GEN-LAST:event_btnsAddItemMouseClicked

    private void txtCraftShopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCraftShopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCraftShopActionPerformed
DefaultListModel CraftShopItems = new DefaultListModel();
ArrayList<String> Craftshop = new ArrayList(30);
    private void btncAddItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncAddItemMouseClicked
        // TODO add your handling code here:
    
        CraftShopItems.addElement(txtCraftShop.getText());
        Craftshop.add("{{:" + txtCraftShop.getText() + "}}");
	lstCraftShop.setModel(CraftShopItems);
        
    }//GEN-LAST:event_btncAddItemMouseClicked

    private void txtTavernActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTavernActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTavernActionPerformed
DefaultListModel TavernL = new DefaultListModel();
ArrayList<String> Tavern = new ArrayList(30);
    private void btnAddTavernItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddTavernItemMouseClicked
        // TODO add your handling code here:
        TavernL.addElement(txtTavern.getText());
        Tavern.add("{{:" + txtTavern.getText() + "}}");
	lstTavern.setModel(TavernL);
    }//GEN-LAST:event_btnAddTavernItemMouseClicked
DefaultListModel AideL = new DefaultListModel();
ArrayList<String> Aide =  new ArrayList(30);
    private void btnAddAideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddAideMouseClicked
        // TODO add your handling code here:
           
AideL.addElement(txtAide.getText());
        Aide.add("{{:" + txtAide.getText() + "}}");
	lstAide.setModel(AideL);
    }//GEN-LAST:event_btnAddAideMouseClicked

    private void btnGenerateCityPageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGenerateCityPageMouseClicked
  
        try {
            new File("C:\\UWOTextFiles\\Cities\\" + txtNameOfCity.getText() + "Market").mkdirs();
            new File("C:\\UWOTextFiles\\Cities\\" + txtNameOfCity.getText() + "ItemShop").mkdirs();
            new File("C:\\UWOTextFiles\\Cities\\" + txtNameOfCity.getText() + "CraftShop").mkdirs();
            new File("C:\\UWOTextFiles\\Cities\\" + txtNameOfCity.getText() + "Tavern").mkdirs();
            String MarketFile = "C:/UWOTextFiles/Cities/" +txtNameOfCity.getText()+ "Market/"+"Market.txt";
            String FileName = "C:/UWOTextFiles/Cities/" +txtNameOfCity.getText()+".txt";
            String ItemShop = "C:/UWOTextFiles/Cities/" +txtNameOfCity.getText()+"ItemShop/"+"ItemShop.txt";
            String CraftShop = "C:/UWOTextFiles/Cities/" +txtNameOfCity.getText()+ "CraftShop/" + "CraftShop.txt";
            String tavern = "C:/UWOTextFiles/Cities/" +txtNameOfCity.getText()+ "Tavern/"+"Tavern.txt";
            File MarketF = new File(MarketFile);
            File IShop = new File(ItemShop);
            File cShop = new File(CraftShop);
            File tvn = new File(tavern);
            try {
                MarketF.createNewFile();
                IShop.createNewFile();
                cShop.createNewFile();
                tvn.createNewFile();
            } catch (IOException ex) {
                Logger.getLogger(CitiesTemplate.class.getName()).log(Level.SEVERE, null, ex);
            }
           
             if (Itemshop.size() != 0)
            {
            ItemFileWrite(ItemShop, Itemshop);
            }
             if (Craftshop.size() != 0)
            { 
            CraftFileWrite(CraftShop, Craftshop);
            }
             
             if (Tavern.size() != 0)
            {
                
            tavernFileWrite(tavern, Tavern);
            
            }
              if (Goods.size() != 0)
            {
                MarketFileWrite(MarketFile, Goods, Items);
            }
            PrintWriter writer;
            
            writer = new PrintWriter(FileName, "UTF-8");
            writer.println(txtDescriptions.getText());
            writer.println("{{-}}");
            writer.println("{{:{{PAGENAME}}/Map}}");
            writer.println("Required Port Permit: " + cboxRegion.getSelectedItem());
            writer.println("Language: " + "{{:" + cboxLanguage.getSelectedItem() +"}}");
            writer.println("{{-}}");
            writer.println("{{#tag: tabview|");
            writer.println("{{PAGENAME}}/Market{{!}}Market");
            writer.println("{{PAGENAME}}/Item Shop{{!}}Item Shop");
            writer.println("{{PAGENAME}}/Craft Shop{{!}}Craft Shop");
            writer.println("{{PAGENAME}}/Shipyard{{!}}Shipyard");
            writer.println("{{PAGENAME}}/Tavern{{!}}Tavern");
            writer.println("{{PAGENAME}}/NPC{{!}}Contact");
            writer.println("}}");
            writer.close();
      
        } catch (FileNotFoundException ex) {
            Logger.getLogger(CitiesTemplate.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(CitiesTemplate.class.getName()).log(Level.SEVERE, null, ex);
        }

                
 
    
            
    }//GEN-LAST:event_btnGenerateCityPageMouseClicked

    private void btnMarketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMarketMouseClicked
        // TODO add your handling code here:
        frmMarket.setVisible(true);
        
    }//GEN-LAST:event_btnMarketMouseClicked

    private void btnItemShopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnItemShopMouseClicked
        // TODO add your handling code here:
        frmItemShop.setVisible(true);
    }//GEN-LAST:event_btnItemShopMouseClicked

    private void btnCraftShopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCraftShopMouseClicked
        // TODO add your handling code here:
        CraftShop.setVisible(true);
    }//GEN-LAST:event_btnCraftShopMouseClicked

    private void btnTavernMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTavernMouseClicked
        // TODO add your handling code here:
        frmTavern.setVisible(true);
    }//GEN-LAST:event_btnTavernMouseClicked

    private void btnResetFormMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetFormMouseClicked
       Tavern.clear();
       TavernL.clear();
       txtTavern.setText("");
       

    }//GEN-LAST:event_btnResetFormMouseClicked

    private void btnResetForm1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetForm1MouseClicked
        // TODO add your handling code here:
        ItemShopItems.clear();
        Itemshop.clear();
    }//GEN-LAST:event_btnResetForm1MouseClicked

    private void btnResetForm2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetForm2MouseClicked
        // TODO add your handling code here:
        Craftshop.clear();
        CraftShopItems.clear();
    }//GEN-LAST:event_btnResetForm2MouseClicked

    private void btnNPCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNPCMouseClicked
        // TODO add your handling code here:
        frmContact.setVisible(true);
        
    }//GEN-LAST:event_btnNPCMouseClicked

    DefaultListModel NPC = new DefaultListModel();
ArrayList<String> NPCS = new ArrayList(30);

    private void btnAddNPCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddNPCMouseClicked
        // TODO add your handling code here:
       NPC.addElement(txtAddNPC.getText());
        NPCS.add("{{:" + txtAddNPC.getText() + "}}");
	lstNPCs.setModel(NPC);
    }//GEN-LAST:event_btnAddNPCMouseClicked

    private void btnResetForm3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetForm3MouseClicked
        // TODO add your handling code here:
        NPCS.clear();
        NPC.clear();
        
    }//GEN-LAST:event_btnResetForm3MouseClicked

    private void btnResetForm4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetForm4MouseClicked
        // TODO add your handling code here:
        
        TradeGoods.clear();
        Goods.clear();
    }//GEN-LAST:event_btnResetForm4MouseClicked

    private void btnClearTemplateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearTemplateMouseClicked
        // TODO add your handling code here:
        txtNameOfCity.setText("");
        txtAide.setText("");
        txtCraftShop.setText("");
        txtDescriptions.setText("");
        txtItemShop.setText("");
        txtNameOfCity.setText("");
        txtPedlarItem.setText("");
        txtTavern.setText("");
        txtTradeGood.setText("");
        Aide.clear();
        AideL.clear();
        CraftShopItems.clear();
        Craftshop.clear();
        Goods.clear();
        ItemShopItems.clear();
        Items.clear();
        Itemshop.clear();
        NPC.clear();
        NPCS.clear();
        PedlarItems.clear();
        Tavern.clear();
        TavernL.clear();
        TradeGoods.clear();
    }//GEN-LAST:event_btnClearTemplateMouseClicked

    private void btnResetForm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetForm1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnResetForm1ActionPerformed

    /**
     * @param args the command line arguments
     */
       
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CitiesTemplate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CitiesTemplate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CitiesTemplate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CitiesTemplate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
  try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CitiesTemplate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame CraftShop;
    private javax.swing.JButton btnAddAide;
    private javax.swing.JButton btnAddItem;
    private javax.swing.JButton btnAddNPC;
    private javax.swing.JButton btnAddTavernItem;
    private javax.swing.JButton btnAddTrade;
    private javax.swing.JButton btnClearTemplate;
    private javax.swing.JButton btnCraftShop;
    private javax.swing.JButton btnGenerateCityPage;
    private javax.swing.JButton btnItemShop;
    private javax.swing.JButton btnMarket;
    private javax.swing.JButton btnNPC;
    private javax.swing.JButton btnResetForm;
    private javax.swing.JButton btnResetForm1;
    private javax.swing.JButton btnResetForm2;
    private javax.swing.JButton btnResetForm3;
    private javax.swing.JButton btnResetForm4;
    private javax.swing.JButton btnTavern;
    private javax.swing.JButton btncAddItem;
    private javax.swing.JButton btnsAddItem;
    public javax.swing.JComboBox<String> cboxLanguage;
    public javax.swing.JComboBox<String> cboxRegion;
    private javax.swing.JFrame frmContact;
    private javax.swing.JFrame frmItemShop;
    private javax.swing.JFrame frmMarket;
    private javax.swing.JFrame frmShipyard;
    private javax.swing.JFrame frmTavern;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JList<String> lstAide;
    private javax.swing.JList<String> lstCraftShop;
    private javax.swing.JList<String> lstItemShop;
    private javax.swing.JList<String> lstMarketGoods;
    private javax.swing.JList<String> lstNPCs;
    private javax.swing.JList<String> lstPedlarGoods;
    private javax.swing.JList<String> lstTavern;
    private javax.swing.JTextField txtAddNPC;
    public javax.swing.JTextField txtAide;
    public javax.swing.JTextField txtCraftShop;
    public javax.swing.JTextArea txtDescriptions;
    public javax.swing.JTextField txtItemShop;
    public javax.swing.JTextField txtNameOfCity;
    public javax.swing.JTextField txtPedlarItem;
    public javax.swing.JTextField txtTavern;
    public javax.swing.JTextField txtTradeGood;
    // End of variables declaration//GEN-END:variables
}
