/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uwowikiaaid;

import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.io.UnsupportedEncodingException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.UIManager;

/**
 *
 * @author Simon
 */
public class Quests extends javax.swing.JFrame {

     public class QuestStep{
        String QuestHeading,QuestDetail;
        
        public void SetHeading( String Heading)
        {
            QuestHeading = Heading;
        }
        public void SetDetail(String Detail)
        {
            QuestDetail = Detail;
        }
        
        public String GetHeading()
        {
            return QuestHeading;
        }
        
        public String GetDetail()
        {
            return QuestDetail;
        }      
          
     }
    /**
     * Creates new form Quests2
     */
    public Quests() {
          
        this.questlist = new QuestStep[15];
        
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLocations = new javax.swing.JLabel();
        btnClear = new javax.swing.JButton();
        txtRewardPart1 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        txtRewardPart2 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        txtRewardPart3 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        txtRewardPart4 = new javax.swing.JTextField();
        txtQuestName = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        btnGenerateText = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cboxCategory = new javax.swing.JComboBox<>();
        lblCategory = new javax.swing.JLabel();
        txtrewCash = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtrewAdv = new javax.swing.JTextField();
        lblSkill1 = new javax.swing.JLabel();
        txtPrequest = new javax.swing.JTextField();
        cboxSkill1 = new javax.swing.JComboBox<>();
        txtNextQuest = new javax.swing.JTextField();
        cboxSkill2 = new javax.swing.JComboBox<>();
        jLabel35 = new javax.swing.JLabel();
        cboxSkill3 = new javax.swing.JComboBox<>();
        jLabel36 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cboxrank1 = new javax.swing.JComboBox<>();
        cboxrank2 = new javax.swing.JComboBox<>();
        cboxrank3 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDetails = new javax.swing.JTextArea();
        lblDetails = new javax.swing.JLabel();
        txtLocation = new javax.swing.JTextField();
        btnAddLocation = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstQuestSteps = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtQuestDetails = new javax.swing.JTextArea();
        lblQuestDetails = new javax.swing.JLabel();
        btnAddStep = new javax.swing.JButton();
        txtStepHeader = new javax.swing.JTextField();
        lblHeading = new javax.swing.JLabel();
        cboxDifficulty = new javax.swing.JComboBox<>();
        lblDifficulty = new javax.swing.JLabel();
        cboxLanguage = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(714, 410));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblLocations.setText("Locations: ");

        btnClear.setText("Reset Template");
        btnClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClearMouseClicked(evt);
            }
        });
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        jLabel31.setText("Fame:");

        jLabel32.setText("Exp:");

        txtRewardPart3.setToolTipText("");

        jLabel33.setText("Discovery/Item");

        txtRewardPart4.setToolTipText("");

        txtQuestName.setName("txtQuestName"); // NOI18N

        jLabel34.setText("Second Item");

        btnGenerateText.setText("Generate Text");
        btnGenerateText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGenerateTextMouseClicked(evt);
            }
        });
        btnGenerateText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateTextActionPerformed(evt);
            }
        });

        jLabel1.setText("Name of Quest");

        jLabel2.setText("Location of quest");

        cboxCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Category", "Maritime", "Adventure", "Merchant" }));

        lblCategory.setText("Category:");

        txtrewCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrewCashActionPerformed(evt);
            }
        });

        jLabel3.setText("Reward Cash:");

        jLabel4.setText("Advance Payment:");

        lblSkill1.setText("Skill 1");

        cboxSkill1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Skill 1", "accounts", "aboardage", "accuracy", "alcohol trading", "appraisal", "archaeology", "arms", "art", "art trading", "assault", "ballistics", "biology", "body language", "casting", "caution", "collection", "cooking", "crafts trading", "dye trading", "ecological research", "eradication", "escape escape", "evasion", "fabric trading", "fire fighting", "firearms trading", "first aid", "fishing", "food trading", "frugality", "geography", "guard", "gunfire", "gunnery", "handicrafts", "haul", "jewellry trading", "leadership", "linguistics", "livestock trading", "lookout", "luxuries trading", "management", "marching", "medicine trading", "merchandise knowledge", "metal trading metal", "mine detection", "mine laying", "mineral trading mineral", "navigation", "observe", "pathology", "penetration", "perfume trading perfume", "persuasion", "plunder", "procurement", "provisions", "recognition", "reloading", "repair", "request reinforce", "rescue", "rowing", "sail handling", "salvage", "search", "seasoning trading", "sewing", "shipbuilding", "sniping", "sociability", "spice trading", "steering", "storage", "sundries trading", "surgery", "surveying", "survival", "sword mastery", "swordplay", "tactics", "textile trading", "theology", "throwing", "trap", "unlock", "wares trading", "weapons trading", "wining and dining" }));

        cboxSkill2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Skill 2", "accounts", "aboardage", "accuracy", "alcohol trading", "appraisal ", "archaeology", "arms", "art ", "art trading", "assault", "ballistics", "biology ", "body language", "casting", "caution", "collection ", "cooking ", "crafts trading", "dye trading", "ecological research", "eradication", "escape escape", "evasion ", "fabric trading", "fire fighting", "firearms trading", "first aid", "fishing ", "food trading", "frugality", "geography", "guard", "gunfire ", "gunnery", "handicrafts", "haul ", "jewellry trading", "leadership", "linguistics", "livestock trading ", "lookout", "luxuries trading", "management", "marching", "medicine trading", "merchandise knowledge", "metal trading metal", "mine detection", "mine laying ", "mineral trading mineral", "navigation ", "observe ", "pathology ", "penetration ", "perfume trading perfume", "persuasion", "plunder", "procurement ", "provisions", "recognition", "reloading", "repair ", "request reinforce", "rescue", "rowing ", "sail handling ", "salvage ", "search ", "seasoning trading", "sewing ", "shipbuilding", "sniping ", "sociability ", "spice trading ", "steering ", "storage ", "sundries trading", "surgery", "surveying ", "survival ", "sword mastery", "swordplay", "tactics", "textile trading ", "theology ", "throwing ", "trap ", "unlock ", "wares trading", "weapons trading", "wining and dining" }));

        jLabel35.setText("Next Quest:");

        cboxSkill3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Skill 3", "accounts", "aboardage", "accuracy", "alcohol trading", "appraisal ", "archaeology", "arms", "art ", "art trading", "assault", "ballistics", "biology ", "body language", "casting", "caution", "collection ", "cooking ", "crafts trading", "dye trading", "ecological research", "eradication", "escape escape", "evasion ", "fabric trading", "fire fighting", "firearms trading", "first aid", "fishing ", "food trading", "frugality", "geography", "guard", "gunfire ", "gunnery", "handicrafts", "haul ", "jewellry trading", "leadership", "linguistics", "livestock trading ", "lookout", "luxuries trading", "management", "marching", "medicine trading", "merchandise knowledge", "metal trading metal", "mine detection", "mine laying ", "mineral trading mineral", "navigation ", "observe ", "pathology ", "penetration ", "perfume trading perfume", "persuasion", "plunder", "procurement ", "provisions", "recognition", "reloading", "repair ", "request reinforce", "rescue", "rowing ", "sail handling ", "salvage ", "search ", "seasoning trading", "sewing ", "shipbuilding", "sniping ", "sociability ", "spice trading ", "steering ", "storage ", "sundries trading", "surgery", "surveying ", "survival ", "sword mastery", "swordplay", "tactics", "textile trading ", "theology ", "throwing ", "trap ", "unlock ", "wares trading", "weapons trading", "wining and dining" }));

        jLabel36.setText("Previous Quest");

        jLabel5.setText("Skill 2");

        jLabel6.setText("Skill 3");

        cboxrank1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Skill Rank", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16" }));

        cboxrank2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Skill Rank", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16" }));

        cboxrank3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Skill Rank", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16" }));

        txtDetails.setColumns(20);
        txtDetails.setLineWrap(true);
        txtDetails.setRows(5);
        txtDetails.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtDetails);

        lblDetails.setText("Details:");

        btnAddLocation.setText("AddLocation");
        btnAddLocation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddLocationMouseClicked(evt);
            }
        });

        jScrollPane2.setViewportView(lstQuestSteps);

        txtQuestDetails.setColumns(20);
        txtQuestDetails.setRows(5);
        jScrollPane3.setViewportView(txtQuestDetails);

        lblQuestDetails.setText("Details");

        btnAddStep.setText("Add Step");
        btnAddStep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddStepMouseClicked(evt);
            }
        });

        lblHeading.setText("Heading");

        cboxDifficulty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));

        lblDifficulty.setText("Difficulty:");

        cboxLanguage.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Language", "English", "Dutch", "German", "Nordic", "Celtic", "Portuguese", "Spanish", "French", "Italian", "Latin", "Slavic", "Greek", "Arabic", "Ancient Egyptian", "Hebrew", "Turkish", "West African languages", "Swahili", "Persian", "Indian languages", "Mayan languages", "Nahuatl", "Quecha", "Thai/Burmese", "Mon-Khmer languages", "Malay/Tagalog", "Oceanic languages", "Chinese", "Japanese", "Korean" }));

        jLabel7.setText("Language:");

        jLabel8.setText("List of Steps");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSkill1)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboxSkill1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboxSkill2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboxSkill3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cboxrank1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(277, 277, 277)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel31, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel32))
                                        .addComponent(jLabel33))
                                    .addComponent(jLabel34, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtRewardPart1)
                                    .addComponent(txtRewardPart2)
                                    .addComponent(txtRewardPart3)
                                    .addComponent(txtRewardPart4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(cboxrank3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnAddLocation))
                                    .addComponent(txtQuestName, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addComponent(lblLocations, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCategory)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cboxCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtrewAdv, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtrewCash, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(69, 69, 69)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(16, 16, 16)
                                                .addComponent(cboxrank2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(lblDetails))
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblQuestDetails)
                                                    .addComponent(lblHeading))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(txtStepHeader)
                                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btnAddStep))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(btnClear)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(btnGenerateText))))))
                                    .addComponent(cboxDifficulty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel35)
                                    .addComponent(jLabel36)
                                    .addComponent(jLabel7)
                                    .addComponent(lblDifficulty))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNextQuest, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPrequest, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cboxLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(txtQuestName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(txtLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAddLocation))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblLocations))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblCategory)
                                    .addComponent(cboxCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(txtrewCash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(txtrewAdv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSkill1)
                            .addComponent(cboxSkill1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboxrank1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRewardPart1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel31))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRewardPart2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel32))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRewardPart3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel33))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRewardPart4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel34))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(cboxSkill2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(cboxSkill3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cboxrank3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnGenerateText)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnClear)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPrequest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel36))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNextQuest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel35)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblDetails)
                        .addComponent(cboxrank2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(cboxLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboxDifficulty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDifficulty))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAddStep)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtStepHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblHeading))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblQuestDetails)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseClicked
        // TODO add your handling code here:

        txtDetails.setText("");
        txtLocation.setText("");
        txtQuestName.setText("");
        txtRewardPart1.setText("") ;
        txtRewardPart2.setText("") ;
        txtRewardPart3.setText("") ;
        txtRewardPart4.setText("") ;
        txtStepHeader.setText("");
        txtQuestDetails.setText("");
        txtrewAdv.setText("");
        txtrewCash.setText("");
        cboxCategory.setSelectedIndex(0);
        cboxDifficulty.setSelectedIndex(0);
        cboxLanguage.setSelectedIndex(0);
        cboxSkill1.setSelectedIndex(0);
        cboxSkill2.setSelectedIndex(0);
        cboxSkill3.setSelectedIndex(0);
        cboxrank1.setSelectedIndex(0);
        cboxrank2.setSelectedIndex(0);
        cboxrank3.setSelectedIndex(0);
        lblLocations.setText("Locations: ");
        Locations = "";
        Location = "|location =";
        txtPrequest.setText("")               ;
        txtNextQuest.setText("");
        Questlist.clear();
        l = 0;
        

    }//GEN-LAST:event_btnClearMouseClicked

    
    String templateStart= "{{Questinfo/start"; 
    String questname ;
    String templateStart2="}}";
    String templatequestinfo= "{{Questinfo/summary";
    String templatequestinfop= "{{Questinfo/progress";
    String templatequestinfoe = "}}";
    String Locations = "";
    String Location = "|location =" + Locations;
    String skills ;
    String Category;
    String rewCash;
    String rewAdv;
    String rewards;
    String dificulty;
    String skill1;
    String skill2;
    String skill3;
    String Language;
    String details;
    String[] stepsh = new String[11];
    String[] stepsd = new String[11];
    String QuestInfo = "{{Questinfo/progress";
    String QuestInfoend = "{{Questinfo/end}}";
  
    
    
    
    
    private void btnGenerateTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGenerateTextMouseClicked
         try {
             // TODO add your handling code here:
             
             questname = "|name=" + txtQuestName.getText();
             Category =  cboxCategory.getSelectedItem().toString() ;
             
             Location =  Location +  " "+  Locations + " " + Category + " guild";
             
             //Location = "|location =  [[" + txtLocation.getText()  + "]]" + Category + " " +  " Guild";
             rewCash = "|rewCash="+txtrewCash.getText();
             rewAdv = "|rewAdv=" +  txtrewAdv.getText();
             dificulty = "|dificulty=" +  (String) cboxDifficulty.getSelectedItem() .toString() + System.lineSeparator() + "|NextQuest= [[" +txtNextQuest.getText() +"]]" + System.lineSeparator() + "|PreQuest=[[" +txtPrequest.getText() +"]]";
             String item2;
             if (txtRewardPart4.getText() == "")
             {
                 item2 = "";
             }
             else
             {
                 item2 = " Item 2: [[" + txtRewardPart4.getText()+ "]]";
             }
             
             rewards = "EXP: " + txtRewardPart1.getText() +  " Fame:"+ txtRewardPart2.getText()  +"<br>" + " Item or Discovery: [[" + txtRewardPart3.getText()+"]]<br>" + item2;
             
             skill1 = "{{:"+cboxSkill1.getSelectedItem().toString() + "|" + cboxrank1.getSelectedItem().toString()+"}}";
             skill2 = "{{:"+cboxSkill2.getSelectedItem().toString() + "|" + cboxrank2.getSelectedItem().toString()+"}}";
             skill3 = "{{:"+cboxSkill3.getSelectedItem().toString() + "|" + cboxrank3.getSelectedItem().toString()+"}}";
             
             Language =  "{{:"+cboxLanguage.getSelectedItem().toString()+ "|1}}";
             
             if (cboxSkill1.getSelectedItem().toString() == "Skill 1")
             {
                 skill1 = "";
                 
             }
             if(cboxSkill2.getSelectedItem().toString() == "Skill 2")
             {
                 
                 skill2 = "";
                 
             }
             
             if (cboxSkill3.getSelectedItem().toString()== "Skill 3")
             {
                 skill3 = "";
                 
             }
             if (cboxLanguage.getSelectedItem().toString() == "Language"){
                 Language = "";
             }
             skills = "|reqSkills=" + skill1 + skill2 + skill3 + Language;
             
             details = "|details = <poem>" +  txtDetails.getText() + "</poem>";
             
             String[] Information = new String[57];
             
             Information[1] = templateStart;
             Information[2] = questname;
             Information[3]=  templateStart2;
             Information[4] = templatequestinfo;
             Information[5]= Location;
             Information[6] = rewCash;
             Information[7] = rewAdv;
             Information[8] = dificulty;
             Information[9] = skills;
             Information[10] =  details;
             Information[11] = templateStart2;
             Information[12] = templatequestinfop;
             Information[13]  = "|heading = Reward";
             Information[14] = "|details = " +  rewards;
             Information[15] =  templatequestinfoe;
             Information[16] = QuestInfoend;
             String FileName = "C:/UWOTextFiles/Quests/" +txtQuestName.getText()+".txt";
             PrintWriter writer;
             
             writer = new PrintWriter(FileName, "UTF-8");
             writer.println(Information[1]);
             writer.println(Information[2]);
             writer.println(Information[3]);
             writer.println(Information[4]);
             writer.println(Information[5]);
             writer.println(Information[6]);
             writer.println(Information[7]);
             writer.println(Information[8]);
             writer.println(Information[9]);
             writer.println(Information[10]);
             writer.println(Information[11]);
             int j = 1;
             for(j = 1 ; j < Questlist.size() + 1 ; j++ ){
                 writer.println(templatequestinfop);
                 writer.println("|heading= " +questlist[j].GetHeading());
                 writer.println("|details= " + questlist[j].GetDetail());
                 writer.println(templatequestinfoe);
             }
             j = 0;
             writer.println(Information[12]);
             writer.println(Information[13]);
             writer.println(Information[14]);
             writer.println(Information[15]);
             writer.println(Information[16]);
             
             writer.close();
             // Writes the content to the file
             
             // Writes the content to the file
             
             // Writes the content to the file
             
             // Writes the content to the file
         } catch (FileNotFoundException ex) {
             Logger.getLogger(Quests.class.getName()).log(Level.SEVERE, null, ex);
         } catch (UnsupportedEncodingException ex) {
             Logger.getLogger(Quests.class.getName()).log(Level.SEVERE, null, ex);
         }

    }//GEN-LAST:event_btnGenerateTextMouseClicked

    private void btnGenerateTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGenerateTextActionPerformed

    private void txtrewCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrewCashActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrewCashActionPerformed

    private void btnAddLocationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddLocationMouseClicked
        // TODO add your handling code here:

        Locations = Locations + "[[" + txtLocation.getText() + "]]";
        lblLocations.setText("Locations: " + Locations );

        //Locations =  Locations + txtLocation.getText();
    }//GEN-LAST:event_btnAddLocationMouseClicked

   
      QuestStep[] questlist;
     DefaultListModel Questlist = new DefaultListModel();
        int l= 1;
          

    private void btnAddStepMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddStepMouseClicked
        // TODO add your handling code here:
           questlist[l] = new QuestStep();
           questlist[l].SetDetail(txtQuestDetails.getText());
           questlist[l].SetHeading(txtStepHeader.getText());
           
        Questlist.addElement(txtStepHeader.getText());
        
       
        l++;
        txtQuestDetails.setText("");
        txtStepHeader.setText("");
         lstQuestSteps.setModel(Questlist);
    }//GEN-LAST:event_btnAddStepMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
  
    }//GEN-LAST:event_formWindowOpened

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Quests.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Quests.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Quests.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Quests.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
  try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Quests().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddLocation;
    private javax.swing.JButton btnAddStep;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnGenerateText;
    private javax.swing.JComboBox<String> cboxCategory;
    private javax.swing.JComboBox<String> cboxDifficulty;
    private javax.swing.JComboBox<String> cboxLanguage;
    private javax.swing.JComboBox<String> cboxSkill1;
    private javax.swing.JComboBox<String> cboxSkill2;
    private javax.swing.JComboBox<String> cboxSkill3;
    private javax.swing.JComboBox<String> cboxrank1;
    private javax.swing.JComboBox<String> cboxrank2;
    private javax.swing.JComboBox<String> cboxrank3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblCategory;
    private javax.swing.JLabel lblDetails;
    private javax.swing.JLabel lblDifficulty;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JLabel lblLocations;
    private javax.swing.JLabel lblQuestDetails;
    private javax.swing.JLabel lblSkill1;
    private javax.swing.JList<String> lstQuestSteps;
    private javax.swing.JTextArea txtDetails;
    private javax.swing.JTextField txtLocation;
    private javax.swing.JTextField txtNextQuest;
    private javax.swing.JTextField txtPrequest;
    private javax.swing.JTextArea txtQuestDetails;
    private javax.swing.JTextField txtQuestName;
    private javax.swing.JTextField txtRewardPart1;
    private javax.swing.JTextField txtRewardPart2;
    private javax.swing.JTextField txtRewardPart3;
    private javax.swing.JTextField txtRewardPart4;
    private javax.swing.JTextField txtStepHeader;
    private javax.swing.JTextField txtrewAdv;
    private javax.swing.JTextField txtrewCash;
    // End of variables declaration//GEN-END:variables
}
