package uwowikiaaid;


import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStream;
import java.io.PrintWriter;
import java.io.UnsupportedEncodingException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import static javax.swing.UIManager.get;
import static javax.xml.bind.JAXBIntrospector.getValue;
import static javax.swing.UIManager.get;
import static javax.swing.UIManager.get;
import static javax.swing.UIManager.get;
import static javax.swing.UIManager.get;
import static javax.swing.UIManager.get;
import static javax.swing.UIManager.get;
import static javax.swing.UIManager.get;
import static javax.swing.UIManager.get;
import static javax.swing.UIManager.get;
import static javax.swing.UIManager.get;
import static javax.swing.UIManager.get;
import static javax.swing.UIManager.get;
import static javax.swing.UIManager.get;
import static javax.swing.UIManager.get;
import static javax.swing.UIManager.get;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Simon
 */
public class Quests extends javax.swing.JFrame {

    /**
     * Creates new form QuestTemplate
     */
    public Quests() {
        initComponents();
          setDefaultCloseOperation(Quests.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtStep1b4 = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtSte = new javax.swing.JTextField();
        txtQuestName = new javax.swing.JTextField();
        btnGenerateText = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cboxCategory = new javax.swing.JComboBox<>();
        lblCategory = new javax.swing.JLabel();
        txtrewCash = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtrewAdv = new javax.swing.JTextField();
        cboxDifficulty = new javax.swing.JComboBox<>();
        lblDifficulty = new javax.swing.JLabel();
        lblSkill1 = new javax.swing.JLabel();
        cboxSkill1 = new javax.swing.JComboBox<>();
        cboxSkill2 = new javax.swing.JComboBox<>();
        cboxSkill3 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cboxLanguage = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cboxrank1 = new javax.swing.JComboBox<>();
        cboxrank2 = new javax.swing.JComboBox<>();
        cboxrank3 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDetails = new javax.swing.JTextArea();
        lblDetails = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtStep1b = new javax.swing.JTextArea();
        txtStep1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtStep2b = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtStep2 = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtStep3b = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtStep3 = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtStep5b = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtStep5 = new javax.swing.JTextField();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtStep6b = new javax.swing.JTextArea();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtStep6 = new javax.swing.JTextField();
        jScrollPane8 = new javax.swing.JScrollPane();
        txtStep7b = new javax.swing.JTextArea();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtStep7 = new javax.swing.JTextField();
        jScrollPane9 = new javax.swing.JScrollPane();
        txtStep4b = new javax.swing.JTextArea();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtStep4 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        txtStep9b = new javax.swing.JTextArea();
        jScrollPane11 = new javax.swing.JScrollPane();
        txtStep8b = new javax.swing.JTextArea();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txtStep8 = new javax.swing.JTextField();
        txtStep9 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jScrollPane12 = new javax.swing.JScrollPane();
        txtStep10b = new javax.swing.JTextArea();
        jLabel29 = new javax.swing.JLabel();
        txtStep10 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        txtLocation = new javax.swing.JTextField();
        btnAddLocation = new javax.swing.JButton();
        lblLocations = new javax.swing.JLabel();
        btnClear = new javax.swing.JButton();
        txtRewardPart1 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        txtRewardPart2 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        txtRewardPart3 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        txtRewardPart4 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        txtPrequest = new javax.swing.JTextField();
        txtNextQuest = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();

        txtStep1b4.setColumns(20);
        txtStep1b4.setRows(5);
        jScrollPane6.setViewportView(txtStep1b4);

        jLabel16.setText("Details Step 1");

        jLabel17.setText("Heading for step 1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quest Template");
        setName("frmQuest"); // NOI18N

        txtQuestName.setName("txtQuestName"); // NOI18N

        btnGenerateText.setText("Generate Text");
        btnGenerateText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGenerateTextMouseClicked(evt);
            }
        });
        btnGenerateText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateTextActionPerformed(evt);
            }
        });

        jLabel1.setText("Name of Quest");

        jLabel2.setText("Location of quest");

        cboxCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Category", "Maritime", "Adventure", "Merchant" }));

        lblCategory.setText("Category:");

        txtrewCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrewCashActionPerformed(evt);
            }
        });

        jLabel3.setText("Reward Cash:");

        jLabel4.setText("Advance Payment:");

        cboxDifficulty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));

        lblDifficulty.setText("Difficulty:");

        lblSkill1.setText("Skill 1");

        cboxSkill1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Skill 1", "accounts", "aboardage", "accuracy", "alcohol trading", "appraisal ", "archaeology", "arms", "art ", "art trading", "assault", "ballistics", "biology ", "body language", "casting", "caution", "collection ", "cooking ", "crafts trading", "dye trading", "ecological", "eradication", "escape escape", "evasion ", "fabric trading", "fire fighting", "firearms trading", "first aid", "fishing ", "food trading", "frugality", "geography", "guard", "gunfire ", "gunnery", "handicrafts", "haul ", "jewellry trading", "leadership", "linguistics", "livestock trading ", "lookout", "luxuries trading", "management", "marching", "medicine trading", "merchandise knowledge", "metal trading metal", "mine detection", "mine laying ", "mineral trading mineral", "navigation ", "observe ", "pathology ", "penetration ", "perfume trading perfume", "persuasion", "plunder", "procurement ", "provisions", "recognition", "reloading", "repair ", "request reinforce", "rescue", "rowing ", "sail handling ", "salvage ", "search ", "seasoning trading", "sewing ", "shipbuilding", "sniping ", "sociability ", "spice trading ", "steering ", "storage ", "sundries trading", "surgery", "surveying ", "survival ", "sword mastery", "swordplay", "tactics", "textile trading ", "theology ", "throwing ", "trap ", "unlock ", "wares trading", "weapons trading", "wining and dining" }));

        cboxSkill2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Skill 2", "accounts", "aboardage", "accuracy", "alcohol trading", "appraisal ", "archaeology", "arms", "art ", "art trading", "assault", "ballistics", "biology ", "body language", "casting", "caution", "collection ", "cooking ", "crafts trading", "dye trading", "ecological", "eradication", "escape escape", "evasion ", "fabric trading", "fire fighting", "firearms trading", "first aid", "fishing ", "food trading", "frugality", "geography", "guard", "gunfire ", "gunnery", "handicrafts", "haul ", "jewellry trading", "leadership", "linguistics", "livestock trading ", "lookout", "luxuries trading", "management", "marching", "medicine trading", "merchandise knowledge", "metal trading metal", "mine detection", "mine laying ", "mineral trading mineral", "navigation ", "observe ", "pathology ", "penetration ", "perfume trading perfume", "persuasion", "plunder", "procurement ", "provisions", "recognition", "reloading", "repair ", "request reinforce", "rescue", "rowing ", "sail handling ", "salvage ", "search ", "seasoning trading", "sewing ", "shipbuilding", "sniping ", "sociability ", "spice trading ", "steering ", "storage ", "sundries trading", "surgery", "surveying ", "survival ", "sword mastery", "swordplay", "tactics", "textile trading ", "theology ", "throwing ", "trap ", "unlock ", "wares trading", "weapons trading", "wining and dining" }));

        cboxSkill3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Skill 3", "accounts", "aboardage", "accuracy", "alcohol trading", "appraisal ", "archaeology", "arms", "art ", "art trading", "assault", "ballistics", "biology ", "body language", "casting", "caution", "collection ", "cooking ", "crafts trading", "dye trading", "ecological", "eradication", "escape escape", "evasion ", "fabric trading", "fire fighting", "firearms trading", "first aid", "fishing ", "food trading", "frugality", "geography", "guard", "gunfire ", "gunnery", "handicrafts", "haul ", "jewellry trading", "leadership", "linguistics", "livestock trading ", "lookout", "luxuries trading", "management", "marching", "medicine trading", "merchandise knowledge", "metal trading metal", "mine detection", "mine laying ", "mineral trading mineral", "navigation ", "observe ", "pathology ", "penetration ", "perfume trading perfume", "persuasion", "plunder", "procurement ", "provisions", "recognition", "reloading", "repair ", "request reinforce", "rescue", "rowing ", "sail handling ", "salvage ", "search ", "seasoning trading", "sewing ", "shipbuilding", "sniping ", "sociability ", "spice trading ", "steering ", "storage ", "sundries trading", "surgery", "surveying ", "survival ", "sword mastery", "swordplay", "tactics", "textile trading ", "theology ", "throwing ", "trap ", "unlock ", "wares trading", "weapons trading", "wining and dining" }));

        jLabel5.setText("Skill 2");

        jLabel6.setText("Skill 3");

        cboxLanguage.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Language", "English", "Dutch", "German", "Nordic", "Celtic", "Portuguese", "Spanish", "French", "Italian", "Latin", "Slavic", "Greek", "Arabic", "Ancient Egyptian", "Hebrew", "Turkish", "West African languages", "Sawhili", "Persian", "Indian languages", "Mayan languages", "Nahuatl", "Quecha", "Thai/Burmese", "Mon-Khmer languages", "Malay/Tagalog", "Oceanic languages", "Chinese", "Japanese", "Korean" }));

        jLabel7.setText("Language:");

        cboxrank1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Skill Rank", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16" }));

        cboxrank2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Skill Rank", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16" }));

        cboxrank3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Skill Rank", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16" }));

        txtDetails.setColumns(20);
        txtDetails.setLineWrap(true);
        txtDetails.setRows(5);
        txtDetails.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtDetails);

        lblDetails.setText("Details:");

        txtStep1b.setColumns(20);
        txtStep1b.setLineWrap(true);
        txtStep1b.setRows(5);
        txtStep1b.setWrapStyleWord(true);
        jScrollPane2.setViewportView(txtStep1b);

        jLabel8.setText("Heading for step 1");

        jLabel9.setText("Details Step 1");

        txtStep2b.setColumns(20);
        txtStep2b.setLineWrap(true);
        txtStep2b.setRows(5);
        txtStep2b.setWrapStyleWord(true);
        jScrollPane3.setViewportView(txtStep2b);

        jLabel10.setText("Details Step 2");

        jLabel11.setText("Heading for step 2");

        txtStep3b.setColumns(20);
        txtStep3b.setLineWrap(true);
        txtStep3b.setRows(5);
        txtStep3b.setWrapStyleWord(true);
        jScrollPane4.setViewportView(txtStep3b);

        jLabel12.setText("Details Step 3");

        jLabel13.setText("Heading for step 3");

        txtStep5b.setColumns(20);
        txtStep5b.setLineWrap(true);
        txtStep5b.setRows(5);
        txtStep5b.setWrapStyleWord(true);
        jScrollPane5.setViewportView(txtStep5b);

        jLabel14.setText("Details Step 5");

        jLabel15.setText("Heading for step 5");
        jLabel15.setToolTipText("");

        txtStep6b.setColumns(20);
        txtStep6b.setLineWrap(true);
        txtStep6b.setRows(5);
        txtStep6b.setWrapStyleWord(true);
        jScrollPane7.setViewportView(txtStep6b);

        jLabel18.setText("Details Step 6");

        jLabel19.setText("Heading for step 6");

        txtStep7b.setColumns(20);
        txtStep7b.setLineWrap(true);
        txtStep7b.setRows(5);
        txtStep7b.setWrapStyleWord(true);
        jScrollPane8.setViewportView(txtStep7b);

        jLabel20.setText("Details Step 7");

        jLabel21.setText("Heading for step 7");

        txtStep4b.setColumns(20);
        txtStep4b.setLineWrap(true);
        txtStep4b.setRows(5);
        txtStep4b.setWrapStyleWord(true);
        jScrollPane9.setViewportView(txtStep4b);

        jLabel22.setText("Details Step 4");

        jLabel23.setText("Heading for step 4");

        jLabel24.setText("Please put\n pre quests in details");

        txtStep9b.setColumns(20);
        txtStep9b.setLineWrap(true);
        txtStep9b.setRows(5);
        txtStep9b.setWrapStyleWord(true);
        jScrollPane10.setViewportView(txtStep9b);

        txtStep8b.setColumns(20);
        txtStep8b.setLineWrap(true);
        txtStep8b.setRows(5);
        txtStep8b.setWrapStyleWord(true);
        jScrollPane11.setViewportView(txtStep8b);

        jLabel25.setText("Heading for step 8");

        jLabel26.setText("Details Step 8");

        jLabel27.setLabelFor(txtStep9);
        jLabel27.setText("Heading for step 9");

        jLabel28.setText("Details Step 9");

        txtStep10b.setColumns(20);
        txtStep10b.setLineWrap(true);
        txtStep10b.setRows(5);
        txtStep10b.setWrapStyleWord(true);
        jScrollPane12.setViewportView(txtStep10b);

        jLabel29.setText("Heading for step 10");

        jLabel30.setText("Details Step 10");

        btnAddLocation.setText("AddLocation");
        btnAddLocation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddLocationMouseClicked(evt);
            }
        });

        lblLocations.setText("Locations: ");

        btnClear.setText("Reset Template");
        btnClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClearMouseClicked(evt);
            }
        });

        jLabel31.setText("Fame:");

        jLabel32.setText("Exp:");

        txtRewardPart3.setToolTipText("");

        jLabel33.setText("Discovery/Item");

        txtRewardPart4.setToolTipText("");

        jLabel34.setText("Second Item");

        jLabel35.setText("Next Quest:");

        jLabel36.setText("Previous Quest");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel27)
                                    .addComponent(jLabel28))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtStep9, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtStep7, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                                    .addComponent(jScrollPane10)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel12)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtStep3, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtStep5)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtStep10, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel19)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(23, 23, 23)
                                                        .addComponent(jLabel22))
                                                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING))
                                                .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.TRAILING))
                                            .addComponent(jLabel30, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(16, 16, 16)
                                                .addComponent(jScrollPane12))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(14, 14, 14)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtStep8, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jScrollPane11)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(14, 14, 14)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtStep6, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jScrollPane7)))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(jLabel23)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtStep2, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 41, Short.MAX_VALUE))
                                            .addComponent(txtStep4, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jScrollPane9)
                                            .addComponent(jScrollPane3))))
                                .addGap(94, 94, 94))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtStep1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblDifficulty, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(cboxDifficulty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(cboxLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblSkill1)
                                                .addComponent(jLabel5)
                                                .addComponent(jLabel6))
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(cboxSkill1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(cboxSkill2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(cboxSkill3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(cboxrank2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(cboxrank1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(cboxrank3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel1)
                                                .addComponent(jLabel2))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(txtLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(btnAddLocation))
                                                .addComponent(txtQuestName, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(97, 97, 97)
                                            .addComponent(lblLocations, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel35)
                                            .addComponent(jLabel36))
                                        .addGap(31, 31, 31)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtNextQuest, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtPrequest, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(lblDetails)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(32, 32, 32))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblCategory)
                                                    .addComponent(jLabel3)
                                                    .addComponent(jLabel4))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(cboxCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(txtrewAdv, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtrewCash, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(btnGenerateText)
                                                    .addComponent(btnClear)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel24)
                                                .addGap(125, 125, 125)))))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel31, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel32))
                                .addComponent(jLabel33))
                            .addComponent(jLabel34, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtRewardPart1, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                            .addComponent(txtRewardPart2)
                            .addComponent(txtRewardPart3)
                            .addComponent(txtRewardPart4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(105, 105, 105))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCategory)
                            .addComponent(cboxCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGenerateText)
                            .addComponent(txtRewardPart1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel31))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtrewCash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnClear)
                            .addComponent(txtRewardPart2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel32))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtrewAdv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRewardPart3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel33))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtRewardPart4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel34)))
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDetails)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtStep2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addGap(77, 77, 77))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtStep4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(txtQuestName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAddLocation))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblLocations)
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSkill1)
                            .addComponent(cboxSkill1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboxrank1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cboxSkill2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboxrank2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cboxSkill3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboxrank3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPrequest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel36))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNextQuest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel35))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboxLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDifficulty)
                            .addComponent(cboxDifficulty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtStep1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(jLabel9))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel10)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtStep3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel23))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(txtStep6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtStep5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel18)))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtStep7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(txtStep8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26)
                            .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtStep9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(txtStep10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel30))))
                .addContainerGap())
        );

        jLabel1.getAccessibleContext().setAccessibleName("Name");

        setSize(new java.awt.Dimension(861, 968));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public class QuestStage {
    public String heading;
    public String details;
            }
    String templateStart= "{{Questinfo/start"; 
    String questname ;
    String templateStart2="}}";
    String templatequestinfo= "{{Questinfo/summary";
    String templatequestinfop= "{{Questinfo/progress";
    String templatequestinfoe = "}}";
    String Locations = "";
    String Location = "|location =" + Locations;
    String skills ;
    String Category;
    String rewCash;
    String rewAdv;
    String rewards;
    String dificulty;
    String skill1;
    String skill2;
    String skill3;
    String Language;
    String details;
    String[] stepsh = new String[11];
    String[] stepsd = new String[11];
     /**
     
      
    
       String steps1h;
       String steps1d;
       String steps2h;
       String steps2d;
       String steps3h;
       String steps3d;
       String steps4h;
       String steps4d;
       String steps5h;
       String steps5d;
       String steps6h;
       String steps6d;
       String steps7h;
       String steps7d;
       String steps8h;
       String steps8d;
       String steps9h;
       String steps9d;
       String steps10h;
       String steps10d;
       *  */
    
    String QuestInfo = "{{Questinfo/progress";
    String QuestInfoend = "{{Questinfo/end}}";
   
    private void btnGenerateTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGenerateTextMouseClicked
        // TODO add your handling code here:
        
         questname = "|name=" + txtQuestName.getText();
         Category =  cboxCategory.getSelectedItem().toString() ;
            
          Location =  Location +  " "+  Locations + " " + Category + " guild";
    
             
         //Location = "|location =  [[" + txtLocation.getText()  + "]]" + Category + " " +  " Guild";
         rewCash = "|rewCash="+txtrewCash.getText();
         rewAdv = "|rewAdv=" +  txtrewAdv.getText();
         dificulty = "|dificulty=" +  (String) cboxDifficulty.getSelectedItem() .toString() + System.lineSeparator() + "|NextQuest= [[" +txtNextQuest.getText() +"]]" + System.lineSeparator() + "|PreQuest=[[" +txtPrequest.getText() +"]]";
         String item2;
                if (txtRewardPart4.getText() == "")
                {
                    item2 = "";
                }
                else
                {
                    item2 = " Item 2: [[" + txtRewardPart4.getText()+ "]]";
                }
                        
                            
                        
         rewards = "EXP: " + txtRewardPart1.getText() +  " Fame:"+ txtRewardPart2.getText()  +"<br>" + " Item or Discovery: [[" + txtRewardPart3.getText()+"]]<br>" + item2; 
   
         skill1 = "{{:"+cboxSkill1.getSelectedItem().toString() + "|" + cboxrank1.getSelectedItem().toString()+"}}";
         skill2 = "{{:"+cboxSkill2.getSelectedItem().toString() + "|" + cboxrank2.getSelectedItem().toString()+"}}";
         skill3 = "{{:"+cboxSkill3.getSelectedItem().toString() + "|" + cboxrank3.getSelectedItem().toString()+"}}";
         
         Language =  "{{:"+cboxLanguage.getSelectedItem().toString()+ "|1}}";
          
       if (cboxSkill1.getSelectedItem().toString() == "Skill 1")
         {
              skill1 = "";
 
         }
         if(cboxSkill2.getSelectedItem().toString() == "Skill 2")
         {
             
             skill2 = "";
 
         }
         
       if (cboxSkill3.getSelectedItem().toString()== "Skill 3")
       {
         skill3 = "";
 
         }
         if (cboxLanguage.getSelectedItem().toString() == "Language"){
          Language = "";
         }        
        skills = "|reqSkills=" + skill1 + skill2 + skill3 + Language;
         
         details = "|details = <poem>" +  txtDetails.getText() + "</poem>";
          int z=1;
         if (txtStep1.getDocument().getLength() < 1)
         {
             stepsh[1]="";
             stepsd[1]= ""; 
        }else 
         {
              stepsh[1] = "|heading="+ txtStep1.getText();
             stepsd[1] = "|details=1)"+ txtStep1b.getText();
         }
        
       if (txtStep2.getDocument().getLength() < 1)
         {
             stepsh[2]="";
             stepsd[2]= ""; 
        }else 
         {
              stepsh[2] = "|heading="+ txtStep2.getText();
             stepsd[2] = "|details=2)"+ txtStep2b.getText();
         }
       
        if (txtStep3.getDocument().getLength() < 1)
         {
             stepsh[3]="";
             stepsd[3]= ""; 
        }else 
         {
              stepsh[3] = "|heading="+ txtStep3.getText();
             stepsd[3] = "|details=3)"+ txtStep3b.getText();
         }
        
         if (txtStep4.getDocument().getLength() < 1)
         {
             stepsh[4]="";
             stepsd[4]= ""; 
        }else 
         {
              stepsh[4] = "|heading="+ txtStep4.getText();
             stepsd[4] = "|details=4)"+ txtStep4b.getText();
         }
         
          if (txtStep5.getDocument().getLength() < 1)
         {
             stepsh[5]="";
             stepsd[5]= ""; 
        }else 
         {
              stepsh[5] = "|heading="+ txtStep5.getText();
             stepsd[5] = "|details=5)"+ txtStep5b.getText();
         }
          
          
        if (txtStep6.getDocument().getLength() < 1)
         {
             stepsh[6]="";
             stepsd[6]= ""; 
        }else 
         {
              stepsh[6] = "|heading="+ txtStep6.getText();
             stepsd[6] = "|details=6)"+ txtStep6b.getText();
         }
        
         if (txtStep7.getDocument().getLength() < 1)
         {
             stepsh[7]="";
             stepsd[7]= ""; 
        }else 
         {
              stepsh[7] = "|heading="+ txtStep7.getText();
             stepsd[7] = "|details=7)"+ txtStep7b.getText();
         }
          
          if (txtStep8.getDocument().getLength() < 1)
         {
             stepsh[8]="";
             stepsd[8]= ""; 
        }else 
         {
              stepsh[8] = "|heading="+ txtStep8.getText();
             stepsd[8] = "|details=8)"+ txtStep8b.getText();
         } 
          
       if (txtStep9.getDocument().getLength() < 1)
         {
             stepsh[9]="";
             stepsd[9]= ""; 
        }else 
         {
              stepsh[9] = "|heading="+ txtStep9.getText();
             stepsd[9] = "|details=9)"+ txtStep9b.getText();
         }
       
           if (txtStep10.getDocument().getLength() < 1)
         {
             stepsh[10]="";
             stepsd[10]= ""; 
        }else 
         {
              stepsh[10] = "|heading="+ txtStep10.getText();
             stepsd[10] = "|details=10)"+ txtStep10b.getText();
         }
      
         String[] Information = new String[57];
                
                Information[1] = templateStart;
                 Information[2] = questname;
                Information[3]=  templateStart2; 
                Information[4] = templatequestinfo;
                Information[5]= Location; 
		Information[6] = rewCash;
		Information[7] = rewAdv;
	        Information[8] = dificulty;
		Information[9] = skills;
		Information[10] =  details; 
		Information[11] = templateStart2;       
                if (stepsh[1] == "")
                {
                    Information[12] = "";
                    Information[13]  = "";
 	            Information[14] =  "";
                    Information[15] = "" ;
                }
                else
                {
                Information[12] = templatequestinfop;
		Information[13]  = stepsh[1];
 	         Information[14] =  stepsd[1]; 
                 Information[15] =  templatequestinfoe;
                }
                
               if (stepsh[2] == "")
                {
                    Information[16] = "";
                    Information[17]  = "";
 	            Information[18] =  "";
                    Information[19] = "" ;
                }
                else
                {
                Information[16] = templatequestinfop;
		Information[17]  = stepsh[2];
 	         Information[18] =  stepsd[2]; 
                 Information[19] =  templatequestinfoe;
                }
               
                if (stepsh[3] == "")
                {
                    Information[20] = "";
                    Information[21]  = "";
 	            Information[22] =  "";
                    Information[23] = "" ;
                }
                else
                {
                Information[20] = templatequestinfop;
		Information[21]  = stepsh[3];
 	         Information[22] =  stepsd[3]; 
                 Information[23] =  templatequestinfoe;
                }
                
           
                if (stepsh[4] == "")
                {
                    Information[24] = "";
                    Information[25]  = "";
 	            Information[26] =  "";
                    Information[27] = "" ;
                }
                else
                {
                Information[24] = templatequestinfop;
		Information[25]  = stepsh[4];
 	         Information[26] =  stepsd[4]; 
                 Information[27] =  templatequestinfoe;
                }
                 
               if (stepsh[5] == "")
                {
                    Information[28] = "";
                    Information[29]  = "";
 	            Information[30] =  "";
                    Information[31] = "" ;
                }
                else
                {
                Information[28] = templatequestinfop;
		Information[29]  = stepsh[5];
 	         Information[30] =  stepsd[5]; 
                 Information[31] =  templatequestinfoe;
                }
               
                if (stepsh[6] == "")
                {
                    Information[32] = "";
                    Information[33]  = "";
 	            Information[34] =  "";
                    Information[35] = "" ;
                }
                else
                {
                Information[32] = templatequestinfop;
		Information[33]  = stepsh[6];
 	        Information[34] =  stepsd[6]; 
                Information[35] =  templatequestinfoe;
                }
                
                 if (stepsh[7] == "")
                {
                    Information[36] = "";
                    Information[37]  = "";
 	            Information[38] =  "";
                    Information[39] = "" ;
                }
                else
                {
                Information[36] = templatequestinfop;
		Information[37]  = stepsh[7];
 	        Information[38] =  stepsd[7]; 
                Information[39] =  templatequestinfoe;
                }
                
                 if (stepsh[8] == "")
                {
                    Information[40] = "";
                    Information[41]  = "";
 	            Information[42] =  "";
                    Information[43] = "" ;
                }
                else
                {
                Information[40] = templatequestinfop;
		Information[41]  = stepsh[8];
 	        Information[42] =  stepsd[8]; 
                Information[43] =  templatequestinfoe;
                }
                
  
                
                 
            if (stepsh[9] == "")
                {
                    Information[44] = "";
                    Information[45]  = "";
 	            Information[46] =  "";
                    Information[47] = "" ;
                }
                else
                {
                Information[44] = templatequestinfop;
		Information[45]  = stepsh[9];
 	        Information[46] =  stepsd[9]; 
                Information[47] =  templatequestinfoe;
                }
           if (stepsh[10] == "")
                {
                    Information[48] = "";
                    Information[49]  = "";
 	            Information[50] =  "";
                    Information[51] = "" ;
                }
                else
                {
                Information[48] = templatequestinfop;
		Information[49]  = stepsh[10];
 	        Information[50] =  stepsd[10]; 
                Information[51] =  templatequestinfoe;
                }
                    Information[52] = templatequestinfop;
		Information[53]  = "|heading = Reward";
 	        Information[54] = "|details = " +  rewards; 
                Information[55] =  templatequestinfoe;
                
                 Information[56] = QuestInfoend;
            String FileName = "C:/UWOTextFiles/Quests/" +txtQuestName.getText()+".txt";
        PrintWriter writer;
        try {
            int i=1;
            writer = new PrintWriter(FileName, "UTF-8");
            do{
                if (Information[i] != ""){
                writer.println(Information[i]);
                
                }
                i++;
            }while (i < 57);
                
    writer.close();
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Quests.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(Quests.class.getName()).log(Level.SEVERE, null, ex);
        }
 
     
      // Writes the content to the file
 
     
      // Writes the content to the file
 
     
      // Writes the content to the file
 
     
      // Writes the content to the file
    
      
            
            
            
        
         
         
         
    }//GEN-LAST:event_btnGenerateTextMouseClicked

    private void btnGenerateTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGenerateTextActionPerformed

    private void txtrewCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrewCashActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrewCashActionPerformed
DefaultListModel LocationList;      // TODO add your handling code here:
    private void btnAddLocationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddLocationMouseClicked
        // TODO add your handling code here:
        
        Locations = Locations + "[[" + txtLocation.getText() + "]]";
        lblLocations.setText("Locations: " + Locations );
        
        
        //Locations =  Locations + txtLocation.getText();
    }//GEN-LAST:event_btnAddLocationMouseClicked

    private void btnClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseClicked
            // TODO add your handling code here:
          
            txtDetails.setText("");
            txtLocation.setText("");
            txtQuestName.setText("");
txtRewardPart1.setText("") ;
txtRewardPart2.setText("") ;
txtRewardPart3.setText("") ;
txtRewardPart4.setText("") ;
txtStep1.setText("");
txtStep1b.setText("");
txtStep2.setText("");
txtStep2b.setText("");
txtStep3.setText("");
txtStep3b.setText("");
txtStep4.setText("");
txtStep4b.setText("");
txtStep5.setText("");
txtStep5b.setText("");
txtStep6.setText("");
txtStep6b.setText("");
txtStep7.setText("");
txtStep7b.setText("");
txtStep8.setText("");
txtStep8b.setText("");
txtStep9.setText("");
txtStep9b.setText("");
txtStep10.setText("");
txtStep10b.setText("");
txtrewAdv.setText("");
txtrewCash.setText("");
cboxCategory.setSelectedIndex(0);
cboxDifficulty.setSelectedIndex(0);
cboxLanguage.setSelectedIndex(0);
cboxSkill1.setSelectedIndex(0);
cboxSkill2.setSelectedIndex(0);
cboxSkill3.setSelectedIndex(0);
cboxrank1.setSelectedIndex(0);
cboxrank2.setSelectedIndex(0);
cboxrank3.setSelectedIndex(0);
Locations= "";
lblLocations.setText("Locations: ");
     txtPrequest.setText("")               ;
     txtNextQuest.setText("");
     
                        
                       
            
    }//GEN-LAST:event_btnClearMouseClicked

        
int i= 1;                                          /*
          booklists.addElement(txtRelbook.getText());
        relbook[i] = txtRelbook.getText();
        lstRelBooks.setModel(booklists);
        i++;
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Quests.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Quests.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Quests.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Quests.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
  try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Quests().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddLocation;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnGenerateText;
    private javax.swing.JComboBox<String> cboxCategory;
    private javax.swing.JComboBox<String> cboxDifficulty;
    private javax.swing.JComboBox<String> cboxLanguage;
    private javax.swing.JComboBox<String> cboxSkill1;
    private javax.swing.JComboBox<String> cboxSkill2;
    private javax.swing.JComboBox<String> cboxSkill3;
    private javax.swing.JComboBox<String> cboxrank1;
    private javax.swing.JComboBox<String> cboxrank2;
    private javax.swing.JComboBox<String> cboxrank3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JLabel lblCategory;
    private javax.swing.JLabel lblDetails;
    private javax.swing.JLabel lblDifficulty;
    private javax.swing.JLabel lblLocations;
    private javax.swing.JLabel lblSkill1;
    private javax.swing.JTextArea txtDetails;
    private javax.swing.JTextField txtLocation;
    private javax.swing.JTextField txtNextQuest;
    private javax.swing.JTextField txtPrequest;
    private javax.swing.JTextField txtQuestName;
    private javax.swing.JTextField txtRewardPart1;
    private javax.swing.JTextField txtRewardPart2;
    private javax.swing.JTextField txtRewardPart3;
    private javax.swing.JTextField txtRewardPart4;
    private javax.swing.JTextField txtSte;
    private javax.swing.JTextField txtStep1;
    private javax.swing.JTextField txtStep10;
    private javax.swing.JTextArea txtStep10b;
    private javax.swing.JTextArea txtStep1b;
    private javax.swing.JTextArea txtStep1b4;
    private javax.swing.JTextField txtStep2;
    private javax.swing.JTextArea txtStep2b;
    private javax.swing.JTextField txtStep3;
    private javax.swing.JTextArea txtStep3b;
    private javax.swing.JTextField txtStep4;
    private javax.swing.JTextArea txtStep4b;
    private javax.swing.JTextField txtStep5;
    private javax.swing.JTextArea txtStep5b;
    private javax.swing.JTextField txtStep6;
    private javax.swing.JTextArea txtStep6b;
    private javax.swing.JTextField txtStep7;
    private javax.swing.JTextArea txtStep7b;
    private javax.swing.JTextField txtStep8;
    private javax.swing.JTextArea txtStep8b;
    private javax.swing.JTextField txtStep9;
    private javax.swing.JTextArea txtStep9b;
    private javax.swing.JTextField txtrewAdv;
    private javax.swing.JTextField txtrewCash;
    // End of variables declaration//GEN-END:variables
}
