
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uwowikiaaid;

import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.io.UnsupportedEncodingException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JTable;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Simon
 */
public class Ship extends javax.swing.JFrame {

    /**
     * Creates new form Ship
     */
    public Ship() {
         initComponents();
        model.addColumn("City"); 
        model.addColumn("Price"); 
        model.addColumn("Material"); 
        model.addColumn("Hull");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtAdventure = new javax.swing.JTextField();
        txtTrade = new javax.swing.JTextField();
        txtBattle = new javax.swing.JTextField();
        txtVertical = new javax.swing.JTextField();
        txtDurability = new javax.swing.JTextField();
        txtHorizontal = new javax.swing.JTextField();
        txtRow = new javax.swing.JTextField();
        txtArmour = new javax.swing.JTextField();
        txtTurn = new javax.swing.JTextField();
        txtWave = new javax.swing.JTextField();
        txtSailors = new javax.swing.JTextField();
        TxtCannon = new javax.swing.JTextField();
        txtHold = new javax.swing.JTextField();
        txtStudding = new javax.swing.JTextField();
        txtFigure = new javax.swing.JTextField();
        txtCrest = new javax.swing.JTextField();
        txtExtraArmouring = new javax.swing.JTextField();
        txtBroadside = new javax.swing.JTextField();
        txtStern = new javax.swing.JTextField();
        txtSpecial = new javax.swing.JTextField();
        btnAddSkill = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstListOfSkills = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtBow = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtShipDescription = new javax.swing.JTextArea();
        jLabel22 = new javax.swing.JLabel();
        btnGenerateTemplate = new javax.swing.JButton();
        txtCity = new javax.swing.JTextField();
        txtCost = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        btnAddBuildLocation = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblBuildLocation = new javax.swing.JTable();
        cboxShipSkills = new javax.swing.JComboBox<>();
        txtShipName = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        btnResetTemplate = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        cboxPaneling = new javax.swing.JComboBox<>();
        cboxMaterial = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtCrest.setMaximumSize(new java.awt.Dimension(59, 20));

        txtBroadside.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        txtStern.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        btnAddSkill.setText("Add Skill");
        btnAddSkill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSkillActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(lstListOfSkills);

        jLabel1.setText("Adventure:");

        jLabel2.setText("Trade:");

        jLabel3.setText("Battle:");

        jLabel4.setText("Vertical Sail:");

        jLabel5.setText("Horizontal Sail");

        jLabel6.setText("Row Power:");

        jLabel7.setText("Armour:");

        jLabel8.setText("Durability:");

        jLabel9.setText("Turn Speed:");

        jLabel10.setText("Wave Resistance:");

        jLabel11.setText("Sailors:");

        jLabel12.setText("Cannon Chambers:");

        jLabel13.setText("Hold:");

        jLabel14.setText("Studding Sails:");

        jLabel15.setText("Figurehead:");

        jLabel16.setText("Crest:");

        jLabel17.setText("Special Equipment:");

        jLabel18.setText("Extra Armouring:");

        jLabel19.setText("Broadside:");

        jLabel20.setText("Stern:");

        txtBow.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        jLabel21.setText("Bow:");

        txtShipDescription.setColumns(20);
        txtShipDescription.setRows(5);
        jScrollPane2.setViewportView(txtShipDescription);

        jLabel22.setText("Ship Description:");

        btnGenerateTemplate.setToolTipText("");
        btnGenerateTemplate.setLabel("Generate Template");
        btnGenerateTemplate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGenerateTemplateMouseClicked(evt);
            }
        });

        jLabel23.setText("Material:");

        jLabel24.setText("Cost:");

        jLabel25.setText("City:");

        btnAddBuildLocation.setText("Add Build Location");
        btnAddBuildLocation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddBuildLocationMouseClicked(evt);
            }
        });

        tblBuildLocation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "City", "Cost", "Material", "Hull"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblBuildLocation);

        cboxShipSkills.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ship Skill", "Enhance ship handling", "Emergency acceleration", "Rowing Assistance", "Direct hit prevention", "Casting net", "Recreation room", "Adjutant's cabin", "Improved rudder", "Flotsam search", "High lookout", "Hauling assistance", "Lifeboat", "Shipwright's quarters", "Sail sewing skill", "Military Camouflage", "Library", "Reference Room", "Moored mine", "Camouflaged Hold", "Improved Hold", "Galley", "Workshop", "Wind-resistant mast", "Wave-resistant armouring", "Fireproof wall", "Earthquake-proof Hold", "Domestic livestock room", "Sanitation Room", "Everyday Item Storage", "Manufactured Item Storage", "General Luxury Goods Storage", "Quality Luxury Goods Storage", "Quality Cabin", "Paymaster Cabin", "Heavy bombing", "Explosive shell", "Armouring deterioration bullet", "Armour piercing bullet", "Special smoke bomb", "Intensive charge", "Improved gun port", "Demolition work", "Training bomb", "Pre-emptive attack", "Special sterncastle", "Attack prevention net", "Improved ram", "Special ram", "Ramming tactics", "Set fire", "Cooperation enhancement", "Command post", "Repai support", "Intensive repair", "Medical support", "Bullet-proof armouring", "Drainage pump", "Sea mine search", "Sea mine removal", "Special sea mine", "Roaring sea mine", "Improved sea mine", "Assault Deck Battle", "Evade Melee Battle", "Welcome Melee Battle", "Deck Barrier", "Watertight Bulkhead", "Nanban Trade Preference", "Gunboat Refit", "Armoured Ship Refit", "Melee Battle Ship Refit", "Exploration Ship Refit" }));

        jLabel26.setText("Ship Name:");

        btnResetTemplate.setText("Reset Form");
        btnResetTemplate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnResetTemplateMouseClicked(evt);
            }
        });

        jLabel27.setText("Hull:");

        cboxPaneling.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hull", "Small flush deck style hull", "Medium flush deck style hull", "Large flush deck style hull ", "Medium 2 decked hull", "Large 2 decked hull ", "Medium 3 decked hull ", "Large 3 decked hull", "Small Row Boat ", "Medium Row Boat ", "Large Row Boat", "Large 2 decked Row Boat", "Large 3 decked Row Boat", "E. Asian Standard Hull ", "E. Asian Heavy Hull", "E. Asian Large Row Boat", "Modified E. Asian Heavy Hull ", "Improved E. Asian Heavy Hull", "Modified E. Asian Large Row Boat", "Official Large 2 decked hull", "Official Large 3 decked hull ", "Official Large Row Boat ", "Official Large 2 decked Row Boat ", "Official Large 3 decked Row Boat", "Commander's Medium Flush Deck Style Hull", "Commander's Medium 2 decked hull", "Commander's Medium Row Boat ", "Improved Double-Shelled Heavy Hull ", "Special Large 2 decked hull ", "Custom Large 2 decked Row Boat ", "General Small Hull ", "General Medium Hull ", "General Large Hull", "General Small Row Boat", "General Medium Row Boat ", "General Large Row Boat" }));

        cboxMaterial.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Material", "Cedar Paneling", "Celebratory Metal Paneling", "Celebratory Wooden Paneling ", "Ceremonial Metal Paneling ", "Ceremonial Wooden Paneling", "Copper-coated Paneling", "Elm Paneling", "Festival Metal Paneling ", "Festival Wooden Paneling ", "Military Paneling ", "Military Wooden Paneling ", "Holy Roman Imperial Guard Paneling ", "Holy Roman Imperial Paneling ", "Holy Roman Imperial Wooden Paneling ", "Iron-plated Paneling", "Mahogany Paneling", "Noble Metal Paneling ", "Noble Wooden Paneling ", "Nocturnal Metal Paneling ", "Nocturnal Wooden Paneling", "Oak Paneling", "Red Pine Paneling", "Rosewood Paneling", "Teak Paneling" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel26))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtHorizontal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                                    .addComponent(txtVertical, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addComponent(txtBattle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addComponent(txtTrade, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addComponent(txtRow, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addComponent(txtAdventure))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(150, 150, 150)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(TxtCannon, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSailors, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtWave, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTurn, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDurability, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                                    .addComponent(txtArmour))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel13)
                                                    .addComponent(jLabel14)
                                                    .addComponent(jLabel15))
                                                .addGap(30, 30, 30)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(txtHold, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtStudding, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(txtFigure, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel17)
                                                    .addComponent(jLabel16))
                                                .addGap(10, 10, 10)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(txtCrest, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                                                    .addComponent(txtSpecial))))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(26, 26, 26)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel19)
                                                    .addComponent(jLabel20)
                                                    .addComponent(jLabel21))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(txtBow, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                                                    .addComponent(txtBroadside)
                                                    .addComponent(txtStern, javax.swing.GroupLayout.Alignment.LEADING)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnGenerateTemplate))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtExtraArmouring, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnResetTemplate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addComponent(txtShipName, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cboxShipSkills, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAddSkill))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(jLabel27)
                                .addGap(18, 18, 18)
                                .addComponent(cboxPaneling, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnAddBuildLocation))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(43, 43, 43)
                            .addComponent(jLabel25)
                            .addGap(18, 18, 18)
                            .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(26, 26, 26)
                            .addComponent(jLabel24)
                            .addGap(18, 18, 18)
                            .addComponent(txtCost, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel23)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cboxMaterial, 0, 1, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(84, 84, 84)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtShipName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAdventure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtArmour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(txtHold, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(txtBroadside, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(txtDurability, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(txtStudding, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20)
                            .addComponent(txtStern, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBattle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(txtTurn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtVertical, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10)
                                    .addComponent(txtWave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtHorizontal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11)
                                    .addComponent(txtSailors, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17)
                                    .addComponent(txtSpecial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(btnGenerateTemplate))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(txtFigure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21)
                            .addComponent(txtBow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCrest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(txtRow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12)
                        .addComponent(TxtCannon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel18))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtExtraArmouring, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnResetTemplate)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cboxShipSkills, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAddSkill))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25)
                    .addComponent(cboxMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(cboxPaneling, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddBuildLocation))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    DefaultTableModel model = new DefaultTableModel();
    
    private void btnAddBuildLocationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddBuildLocationMouseClicked
    
        
        model.addRow(new Object[]{txtCity.getText(), txtCost.getText(),cboxMaterial.getSelectedItem().toString(), cboxPaneling.getSelectedItem().toString()});
        // TODO add your handling code here:
        
        tblBuildLocation.setModel(model);
    }//GEN-LAST:event_btnAddBuildLocationMouseClicked
    DefaultListModel Skilllist = new DefaultListModel();
    private void btnAddSkillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSkillActionPerformed
        // TODO add your handling code here:
        Skilllist.addElement(cboxShipSkills.getSelectedItem().toString());
        lstListOfSkills.setModel(Skilllist);
    }//GEN-LAST:event_btnAddSkillActionPerformed

    private void btnGenerateTemplateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGenerateTemplateMouseClicked
        try {
            // TODO add your handling code here:
            String FileName = "C:/UWOTextFiles/Ships/" +txtShipName.getText()+".txt";
            PrintWriter writer;
            writer = new PrintWriter(FileName, "UTF-8");
            writer.println("{{ShipInfo");
            writer.println("|ShipDecscription = " + txtShipDescription.getText());
            writer.println("|Adventure= " + txtAdventure.getText());
            writer.println("|Trade= " + txtTrade.getText());
            writer.println("|Battle= " + txtBattle.getText());
            writer.println("|Vertical= " + txtVertical.getText());
            writer.println("|Horizontal= " + txtHorizontal.getText());
            writer.println("|RowPower= " + txtRow.getText());
            writer.println("|Armour= " + txtArmour.getText());
            writer.println("|Durability= " + txtDurability.getText());
            writer.println("|TurnSpeed= " + txtTurn.getText());
            writer.println("|WaveResistance= "+ txtWave.getText());
            writer.println("|Sailors/Max= "+ txtSailors.getText());
            writer.println("|Cannon= " + TxtCannon.getText());
            writer.println("|Hold= " + txtHold.getText());
            writer.println("|StuddingSails= " + txtStudding.getText());
            writer.println("|FigureHead= " + txtFigure.getText());
            writer.println("|Crest= "+txtCrest.getText());
            writer.println("|SpecialEquip= "+txtSpecial.getText());
            writer.println("|Armouring= " + txtExtraArmouring.getText());
            writer.println("|Broadside= " + txtBroadside.getText());
            writer.println("|Stern= " + txtStern.getText());
            writer.println("|Bow= " + txtBow.getText());
            
            for(int i = 0; i < Skilllist.getSize()  ; i++)
            {
                writer.println("|ShipSkill" + (i+1) + " = " + Skilllist.getElementAt(i));
            }
            writer.println("}}<br>");
            
            writer.println("{| class=\"UWtable burlywood\"");
            writer.println("!City");
            writer.println("![[File:Price.png]]");
            writer.println("!Material");
            writer.println("!Hull");
            writer.println("|-");
           // for(int k = 0;k < model.getRowCount(); k++)
           // {
           int j = 0;
           do{
                writer.println("|"+model.getValueAt(j, 0));
                writer.println("|"+model.getValueAt(j, 1));
                writer.println("|"+model.getValueAt(j,2));
                writer.println("|"+model.getValueAt(j,3));
                writer.println("|-");
                        
               j++;
           }while(j < model.getRowCount());
        //    }
            writer.println("|}");
            writer.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Ship.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedEncodingException ex)
        {
            Logger.getLogger(Ship.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGenerateTemplateMouseClicked

    private void btnResetTemplateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetTemplateMouseClicked
        // TODO add your handling code here:
        txtAdventure.setText("");
txtArmour.setText("");
txtBattle.setText("");
txtBow.setText("");
txtBroadside.setText("");
txtCity.setText("");
txtCost.setText("");
txtCrest.setText("");
txtDurability.setText("");
txtExtraArmouring.setText("");
txtFigure.setText("");
txtHold.setText("");
txtHorizontal.setText("");
cboxMaterial.setSelectedIndex(0);
cboxPaneling.setSelectedIndex(0);
txtRow.setText("");
txtSailors.setText("");
txtShipDescription.setText("");
txtShipName.setText("");
txtSpecial.setText("");
txtStern.setText("");
txtStudding.setText("");
txtTrade.setText("");
txtTurn.setText("");
txtVertical.setText("");
txtWave.setText("");
Skilllist.clear();
cboxShipSkills.setSelectedIndex(0);
int f = 0;
do
{
    model.removeRow(f);
}while(model.getRowCount() != 0);

    }//GEN-LAST:event_btnResetTemplateMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws ClassNotFoundException {
       

        try {
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
            * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
            */
            try {
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } catch (ClassNotFoundException ex) {
                java.util.logging.Logger.getLogger(Ship.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                java.util.logging.Logger.getLogger(Ship.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                java.util.logging.Logger.getLogger(Ship.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                java.util.logging.Logger.getLogger(Ship.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            //</editor-fold>
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
            * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
            */
            try {
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } catch (ClassNotFoundException ex) {
                java.util.logging.Logger.getLogger(Skills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                java.util.logging.Logger.getLogger(Skills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                java.util.logging.Logger.getLogger(Skills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                java.util.logging.Logger.getLogger(Skills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            //</editor-fold>
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
            /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new Ship().setVisible(true);
                }
            });
        } catch (InstantiationException ex) {
            Logger.getLogger(Ship.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(Ship.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(Ship.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtCannon;
    private javax.swing.JButton btnAddBuildLocation;
    private javax.swing.JButton btnAddSkill;
    private javax.swing.JButton btnGenerateTemplate;
    private javax.swing.JButton btnResetTemplate;
    private javax.swing.JComboBox<String> cboxMaterial;
    private javax.swing.JComboBox<String> cboxPaneling;
    private javax.swing.JComboBox<String> cboxShipSkills;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> lstListOfSkills;
    private javax.swing.JTable tblBuildLocation;
    private javax.swing.JTextField txtAdventure;
    private javax.swing.JTextField txtArmour;
    private javax.swing.JTextField txtBattle;
    private javax.swing.JTextField txtBow;
    private javax.swing.JTextField txtBroadside;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtCost;
    private javax.swing.JTextField txtCrest;
    private javax.swing.JTextField txtDurability;
    private javax.swing.JTextField txtExtraArmouring;
    private javax.swing.JTextField txtFigure;
    private javax.swing.JTextField txtHold;
    private javax.swing.JTextField txtHorizontal;
    private javax.swing.JTextField txtRow;
    private javax.swing.JTextField txtSailors;
    private javax.swing.JTextArea txtShipDescription;
    private javax.swing.JTextField txtShipName;
    private javax.swing.JTextField txtSpecial;
    private javax.swing.JTextField txtStern;
    private javax.swing.JTextField txtStudding;
    private javax.swing.JTextField txtTrade;
    private javax.swing.JTextField txtTurn;
    private javax.swing.JTextField txtVertical;
    private javax.swing.JTextField txtWave;
    // End of variables declaration//GEN-END:variables
}
