/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uwowikiaaid;

import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.io.UnsupportedEncodingException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;

/**
 *
 * @author Simon
 */
public class TradeGoods extends javax.swing.JFrame {

    /**
     * Creates new form TradeGoods
     */
    public TradeGoods() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtItemName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cboxType = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cboxSpecialty = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDesc = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        cboxaqs = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblBuy = new javax.swing.JLabel();
        txtBuy = new javax.swing.JTextField();
        btnBuyFrom = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        lblMadeFrom = new javax.swing.JLabel();
        txtMadeFrom = new javax.swing.JTextField();
        btnMadeFrom = new javax.swing.JButton();
        lblRelBook = new javax.swing.JLabel();
        txtRelBook = new javax.swing.JTextField();
        btnRelBook = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        lblToMake = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtToMake = new javax.swing.JTextField();
        btnToMake = new javax.swing.JButton();
        btnGenTemplate = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        btnResetTemplate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Name:");

        cboxType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alcohol", "Arms", "Artwork", "Crafts", "Dyes", "Fabrics", "Fragrances", "Fibers", "Firearms", "Foodstuffs", "Livestock", "Luxury", "Medicine", "Ores", "Precious Metals", "Precious Stones", "Spices", "Sundries", "Wares", "Seasonings" }));

        jLabel2.setText("Type:");

        jLabel3.setText("Specialty");

        cboxSpecialty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Iberia", "Italy and Southern France", "The Balkans", "Caribbean Sea", "E Coast of Latin America", "W Coast of Latin America", "Northern France", "The Netherlands", "The British Isles", "Germany", "Northern Europe", "Turkey", "The Near East", "North Africa", "Arabia", "Persia", "West Africa", "East Africa", "India", "Southeast Asia", "Indo-China", "Oceania", "Korea", "Japan", "South China", "Taiwan", "North America" }));

        txtDesc.setColumns(20);
        txtDesc.setLineWrap(true);
        txtDesc.setRows(5);
        jScrollPane1.setViewportView(txtDesc);

        jLabel4.setText("Description:");

        cboxaqs.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cooking", "Sewing", "Casting", "Handicrafts", "Storage", "Alchemy", "Linguistics", "Nanban" }));

        jLabel5.setText("Aquisition");

        jLabel6.setText("Buy from:");

        lblBuy.setText("City:");

        btnBuyFrom.setText("Add City");
        btnBuyFrom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuyFromMouseClicked(evt);
            }
        });

        jLabel7.setText("Made from:");

        lblMadeFrom.setText("Made From:");

        btnMadeFrom.setText("Add Ingredient");
        btnMadeFrom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMadeFromMouseClicked(evt);
            }
        });

        lblRelBook.setText("Related Book:");

        btnRelBook.setText("Related Book");
        btnRelBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRelBookMouseClicked(evt);
            }
        });

        jLabel8.setText("Related Book");

        lblToMake.setText("To Make:");

        jLabel9.setText("To Make:");

        btnToMake.setText("Add Product");
        btnToMake.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnToMakeMouseClicked(evt);
            }
        });

        btnGenTemplate.setText("Generate Template:");
        btnGenTemplate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGenTemplateMouseClicked(evt);
            }
        });

        jLabel10.setText("Price:");

        btnResetTemplate.setText("Reset Template");
        btnResetTemplate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnResetTemplateMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(9, 9, 9)
                                    .addComponent(jLabel5)))
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtBuy, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnBuyFrom)
                                .addContainerGap(22, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cboxType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtItemName, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cboxSpecialty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cboxaqs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblBuy, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtRelBook, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(26, 26, 26)
                                        .addComponent(btnRelBook))
                                    .addComponent(lblRelBook, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(btnGenTemplate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnResetTemplate)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblMadeFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtMadeFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnMadeFrom))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtToMake, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnToMake))
                                    .addComponent(lblToMake, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtItemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboxType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cboxSpecialty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboxaqs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtBuy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuyFrom)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblBuy, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtToMake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnToMake))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblToMake)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtMadeFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMadeFrom))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblMadeFrom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRelBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRelBook)
                    .addComponent(jLabel8))
                .addGap(12, 12, 12)
                .addComponent(lblRelBook, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGenTemplate)
                    .addComponent(btnResetTemplate))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    ArrayList<String>  MadeFrom =new ArrayList(22);
    ArrayList<String>  RelBook =  new ArrayList(16);
    ArrayList<String>  ToMake = new ArrayList(22);
    ArrayList<String>  City = new ArrayList(51);
    int l,n,p,o = 0;
    private void btnGenTemplateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGenTemplateMouseClicked
        // TODO add your handling code here:
          try {
            String Description,ItemName, Specialty, Aquisition, Type;
            ItemName = "|item= " +  txtItemName.getText();
            Description ="|desc= " +  txtDesc.getText();
            Specialty = "|specialty= " +  cboxSpecialty.getSelectedItem().toString();
            Aquisition = "|aqs= "+ cboxaqs.getSelectedItem().toString();
            Type = "|type= " +  cboxType.getSelectedItem().toString();
            String FileName = "C:/UWOTextFiles/TradeGoods/" +txtItemName.getText()+".txt";
            PrintWriter writer;
            writer = new PrintWriter(FileName, "UTF-8");
            writer.println("{{TGnfo |showtable={{{showtable}}} |name={{{1}}} |imgsz={{{2|}}}");
            writer.println(ItemName);
            writer.println(Type);
            writer.println(Specialty);
            writer.println(Description);
            writer.println(Aquisition);
            writer.println("|buy=");
            writer.println("{{TGnfo/Region|p={{{1}}}|Buying|price=");
            
            if (City.size() != 0)
            {
            do
            {
               writer.println(City.get(l));
               l++;
            }while(l < City.size()  );
            writer.println("}}");
            }
            if (ToMake.size() != 0)
            {
            writer.println("|toMake=");
            do
            {
                writer.println(ToMake.get(n));
                n++;    
            }while(n < ToMake.size());
            }
            
            if (MadeFrom.size() != 0)
            {
            writer.println("|madeFrom=");
            do    
            {
                writer.println(MadeFrom.get(o));
                o++;    
            }while(o < MadeFrom.size());
            
            }
            if (RelBook.size() != 0){
                
            
            do
            {
                writer.println(RelBook.get(p));
                p++;
                        
            }while(p < RelBook.size() );
            }
            
                    
            writer.println("}}");
            writer.close();
            
            
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(TradeGoods.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(TradeGoods.class.getName()).log(Level.SEVERE, null, ex);
        }
         p = 0;
         l = 0;
         n = 0;
         o = 0; 
    }//GEN-LAST:event_btnGenTemplateMouseClicked
  
    private void btnToMakeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnToMakeMouseClicked
        // TODO add your handling code here:
        ToMake.add("{{:" + txtToMake.getText() + "}}");
         lblToMake.setText(lblToMake.getText() +" "+ txtToMake.getText());
      
        
    }//GEN-LAST:event_btnToMakeMouseClicked
    
    private void btnMadeFromMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMadeFromMouseClicked
        // TODO add your handling code here:
        MadeFrom.add("{{:" +txtMadeFrom.getText()+"}}");
        lblMadeFrom.setText(lblMadeFrom.getText() + " " + txtMadeFrom.getText());
  
    }//GEN-LAST:event_btnMadeFromMouseClicked
    int k = 1;
    private void btnRelBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRelBookMouseClicked
        // TODO add your handling code here:
        String Format = "|relbook" + k + "=";
        RelBook.add(Format + txtRelBook.getText());
        lblRelBook.setText(lblRelBook.getText() + " " + txtRelBook.getText());
        k++;
        
    }//GEN-LAST:event_btnRelBookMouseClicked

    private void btnBuyFromMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuyFromMouseClicked
        // TODO add your handling code here:
        City.add("{{TGnfo/Price|p={{{1}}}|" + txtBuy.getText() + "|" + txtPrice.getText()+ "}}");
        lblBuy.setText(lblBuy.getText() + " " + txtBuy.getText());
  
    }//GEN-LAST:event_btnBuyFromMouseClicked

    private void btnResetTemplateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetTemplateMouseClicked
        // TODO add your handling code here:
        lblBuy.setText("City:");
        lblMadeFrom.setText("Made from:");
        lblRelBook.setText("Related Book");
        lblToMake.setText("To make:");
        n= 0;
        k=1;
        n = 0;
        p = 0;
        l = 0;
        o =0;
        txtBuy.setText("");
        txtDesc.setText("");
        txtItemName.setText("");
        txtMadeFrom.setText("");
        txtPrice.setText("");
        txtRelBook.setText("");
        txtToMake.setText("");
        City.clear();
        MadeFrom.clear();
        ToMake.clear();
        RelBook.clear();
        cboxSpecialty.setSelectedIndex(0);
        cboxType.setSelectedIndex(0);
        cboxaqs.setSelectedIndex(0);
        
        
        
    }//GEN-LAST:event_btnResetTemplateMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TradeGoods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TradeGoods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TradeGoods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TradeGoods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
  try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TradeGoods().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuyFrom;
    private javax.swing.JButton btnGenTemplate;
    private javax.swing.JButton btnMadeFrom;
    private javax.swing.JButton btnRelBook;
    private javax.swing.JButton btnResetTemplate;
    private javax.swing.JButton btnToMake;
    private javax.swing.JComboBox<String> cboxSpecialty;
    private javax.swing.JComboBox<String> cboxType;
    private javax.swing.JComboBox<String> cboxaqs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBuy;
    private javax.swing.JLabel lblMadeFrom;
    private javax.swing.JLabel lblRelBook;
    private javax.swing.JLabel lblToMake;
    private javax.swing.JTextField txtBuy;
    private javax.swing.JTextArea txtDesc;
    private javax.swing.JTextField txtItemName;
    private javax.swing.JTextField txtMadeFrom;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtRelBook;
    private javax.swing.JTextField txtToMake;
    // End of variables declaration//GEN-END:variables
}
